bcgov/PSSG-SPDBT

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-bc-branches.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-bc-branch-edit.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/steps-business-licence-contact-information-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/steps-business-licence-controlling-members-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/steps-business-licence-information-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/steps-business-licence-selection-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/scss/app.scss

- Business profile GET integration

Business profile integration

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/manual-submission-common.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-request-add-common-modal.component.ts

- SPDBT-2551 - add code for screening type.

Screening - update manual submission

---

src/Spd.Manager.Licence/BizLicenceAppContract.cs
src/Spd.Manager.Licence/BizProfileContract.cs
src/Spd.Manager.Licence/SharedContract.cs

move biz app sole proprietor to profile contract

---

src/Spd.Resource.Repository/Document/DocumentRepository.cs

- add link to licence in document repo

add link to licence in document repo

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/model-desc.models.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/security-screening-portal/components/security-screening-detail.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/security-screening-portal/components/security-screening-list.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-statuses-common.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/status-statistics-common.component.ts

- remove 'Cancelled by' abbreviation SPDBT-2366
- fix info icon alignment - move tooltip to the icon

Screening - remove 'Cancelled by' abbreviation

---

src/Spd.Presentation.Licensing/Controllers/ConfigurationController.cs
src/Spd.Presentation.Screening/Controllers/ConfigurationController.cs

Return environment in configuration

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/login-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile-personal-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-controlling-members.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-employees.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-lookup-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-member-with-swl-add.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/wizard-outside-footer.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/shared.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/scss/_material-overrides.scss

- Common footer
- Fix permit save photo issue
- Business profile validation - wip

Business profile updates

---

src/Spd.Presentation.Screening/ClientApp/src/app/api/models/configuration-response.ts
src/Spd.Presentation.Screening/ClientApp/src/app/api/services/configuration.service.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/interceptors/error.interceptor.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/services/config.service.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/app-header.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/dialog-oops.component.ts

- Display the environment name in the header when not in Production.
- Hide error details when in Production or Training

Screening environment

---

src/Spd.Manager.Licence/BizLicenceAppContract.cs
src/Spd.Manager.Licence/BizLicenceAppMananger.cs
src/Spd.Manager.Licence/SharedContract.cs
src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs

renew contract

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/model-desc.models.ts

SPDBT-1091 - PSSO portal-only label changes

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/permit-wizard-steps/step-permit-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile-licence-criminal-history.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile-licence-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile-licence-police-background.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/worker-licence-wizard-steps/step-worker-licence-user-profile.component.ts

- Update to use accordions in profile

Update to use accordions in profile

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/anonymous/worker-licence-wizard-steps/steps-worker-licence-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/worker-licence-wizard-authenticated-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/worker-licence-wizard-steps/steps-worker-licence-review-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/worker-licence-wizard-steps/step-worker-licence-consent-and-declaration.component.ts

…g the mandate boxes
- SPDBT-2568 User is able to submit Licence application without checking all mandatory check boxes.

SPDBT-2568 User is able to submit when invalid

---

src/Spd.Manager.Licence/LicenceManager.cs
src/Spd.Presentation.Licensing/Controllers/LicenceController.cs
src/Spd.Utilities.LogonUser/ServiceExtensionAuthorization.cs

-allow bcsc and bceid in the one endpoint licece lookup
-return licence no matter it is expired or not in auth and anonymous endpoints

improvement

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-consent-to-release-pssoa.component.ts

- update language: https://justice.gov.bc.ca/jira/browse/SPDBT-588
-

SPDBT-588 - update language

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/model-desc.models.ts

- SPDBT-1091 - missed a change

SPDBT-1091 - PSSO portal-only label change

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/branch-info.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/code-types/model-desc.models.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-managers.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-bc-branches.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-bc-branch-edit.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/worker-licence-wizard-steps/step-worker-licence-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/permit-application.service.ts

Save Business Profile

---

src/Spd.Manager.Licence.UnitTest/LicenceManagerTest.cs
src/Spd.Manager.Licence/LicenceContract.cs
src/Spd.Manager.Licence/LicenceManager.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/LicenceControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/LicenceController.cs
src/Spd.Resource.Repository.IntegrationTest/BizRepositoryTest.cs
src/Spd.Resource.Repository.IntegrationTest/LicenceRepositoryTest.cs
src/Spd.Resource.Repository/Licence/Contract.cs
src/Spd.Resource.Repository/Licence/LicenceRepository.cs

Create new get licence by id endpoint.

Create licence get endpoint

---

src/Spd.Manager.Licence.UnitTest/BizProfileValidationTest.cs
src/Spd.Manager.Licence/BizProfileValidation.cs
src/Spd.Resource.Repository.IntegrationTest/BizRepositoryTest.cs
src/Spd.Resource.Repository/Biz/BizRepository.cs

Modify biz licence put endpoint to set sole proprietor information to null, when biz type is different from sole proprietor.

Modify biz licence put endpoint

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-profile-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-profile-update-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/configuration-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/swl-contact-info.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/address-auto-complete.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/applicant-licence-app.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/applicant-profile.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/biz-licensing.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/biz-profile.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/licence-fee.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/licence.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/login.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/payment.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/permit.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/security-worker-licensing.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/auth-user-bceid.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-lookup-swl.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.helper.ts

- Fix saving / displaying of sole proprietor profile data

Sole proprietor profile updates

---

src/Spd.Resource.Repository.IntegrationTest/LicenceRepositoryTest.cs
src/Spd.Resource.Repository/Licence/LicenceRepository.cs

-modify licence get endpoint, return all data correctly.

return licence holder name correctly

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/validators/form-group.validators.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/step-components/organization-information.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/step-components/vulnerable-sector-question.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/app-header.component.ts

- Language updates
- Generic email/phone validation update
- Fix display of user when logged in as bceid

CRRP organization registration - SPDBT-2382

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/step-components/organization-information.component.ts

Screening SPDBT-2382 - update title

---

src/Spd.Manager.Screening/OrgRegistrationContract.cs
src/Spd.Presentation.Screening/Controllers/OrgRegistrationController.cs

-Be part for https://justice.gov.bc.ca/jira/browse/SPDBT-2382

screening - 2382, be validation

---

src/Spd.Presentation.Licensing/ClientApp/src/app/app.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/app.module.ts

Config loader test

---

src/Spd.Presentation.Screening/ClientApp/src/app/app.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/app.module.ts

- load config from app component to see spinner

Screening - load config

---

src/Spd.Manager.Licence/BizControllingMemberEmployeeContract.cs
src/Spd.Manager.Licence/BizControllingMemberEmployeeManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs

refactor to employee and cm combined to one endpoint

employee and cm combined to one endpoint

---

src/Spd.Manager.Licence.UnitTest/LicenceManagerTest.cs
src/Spd.Manager.Licence/LicenceContract.cs
src/Spd.Manager.Licence/LicenceManager.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/LicenceControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

- Add endpoint to return biz licence information from bizId

Add Licence Query for biz

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrpa-portal/crrpa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/step-components/compensation-question.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/step-components/organization-information.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/pssoa-portal/pssoa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/payment-success.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-appl-submitted.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-application-submitted.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-checklist.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-log-in-options.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-previous-name.component.ts

- SPDBT-2554 - checklist and login page
- SPDBT-2399 - payment confirmation page

Screening bugs - SPDBT-2554, SPDBT-2399

---

splunk/spdLog-splunk.html

splunk source

---

src/Spd.Resource.Repository.IntegrationTest/LicenceApplicationRepositoryTest.cs
src/Spd.Resource.Repository/LicenceApplication/LicenceApplicationRepository.cs

Modify get licence application service. The validation of contact id skips retrieval of aliases when there is no related contact to the application. The modifications include related integrated tests.

Modify get licence application service

---

tools/helm/charts/tools/README.md
tools/helm/charts/tools/sysdig-team-spd.yaml
tools/helm/charts/tools/templates/sysdig-team-spd.yaml

Sysdig setup

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-checklist.component.ts

- Screening SPDBT-2554 - update wording

Screening SPDBT-2554 - update wording

---

src/Spd.Engine.Search/SearchEngine.cs
src/Spd.Resource.Repository.IntegrationTest/ApplicationRepositoryTest.cs
src/Spd.Resource.Repository.IntegrationTest/IntegrationTestSetup.cs
src/Spd.Resource.Repository/Application/ApplicationRepository.Clearance.cs
src/Spd.Resource.Repository/Application/Contract.Application.cs

- https://justice.gov.bc.ca/jira/browse/SPDBT-2629

update sharing for screening

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs
src/Spd.Resource.Repository/PersonLicApplication/PersonLicApplicationRepository.cs

Remove relationship with expired licence when no expired licence Id is provided

Remove relationship with expired licence 

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrpa-portal/crrpa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/steps/step-four.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/pssoa-portal/pssoa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/payment-success.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-appl-submitted.component.ts

- SPDBT-2604 Screening Close button navigation

SPDBT-2604 Screening Close button navigation

---

src/Spd.Resource.Repository/Biz/BizRepository.cs

Remove state code filter for sole proprietor

Remove state code filter for sole proprietor

---

src/Spd.Manager.Printing/Contract.cs
src/Spd.Manager.Printing/Mappings.cs
src/Spd.Manager.Printing/PrintingManager.cs
src/Spd.Presentation.Dynamics/Controllers/Mapping.cs
src/Spd.Presentation.Dynamics/Controllers/PrintingController.cs
src/Spd.Presentation.Dynamics/Models/PrintJobStatusResponse.cs
src/Spd.Resource.Repository/Event/Contract.cs
src/Spd.Resource.Repository/Event/Mappings.cs

- spdbt-2465(BCMP / OpenShift - Fingerprint Letter Job Status)

BCMP / OpenShift - Fingerprint Letter Job Status

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/api.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/licence-app.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/licence-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-controlling-member-invites-component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/main-active-business-licences.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/main-active-swl-permit-licences.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/main-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/main-expired-licences.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/permit-application.service.ts

- Show business licence applications
- Common components between swl/permit and business licence for main page.

Business Licence main 

---

src/Spd.Manager.Screening/UserProfileContract.cs
src/Spd.Manager.Screening/UserProfileManager.cs

-(https://justice.gov.bc.ca/jira/browse/SPDBT-2412)

How to handle authenticated IDIR login not recognised as a valid Org Code

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

Fix biz licence submit services by adding a condition before adding/removing a link between application and licence

Fix biz licence submit services

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/generic-uploads.component.ts
src/Spd.Presentation.Screening/Controllers/ApplicationController.cs
src/Spd.Utilities.Shared/SpdConstants.cs

generic upload update

---

src/Spd.Manager.Licence/Mappings.cs
src/Spd.Resource.Repository.IntegrationTest/BizRepositoryTest.cs
src/Spd.Resource.Repository/Biz/BizRepository.cs
src/Spd.Resource.Repository/Biz/Mappings.cs

Fix biz submit services by skipping modification of email and phone number if sole proprietor licence id is not null

Fix biz submit services

---

src/Spd.Resource.Repository.IntegrationTest/BizRepositoryTest.cs
src/Spd.Resource.Repository.IntegrationTest/LicenceRepositoryTest.cs
src/Spd.Resource.Repository/Application/ApplicationRepository.Application.cs
src/Spd.Resource.Repository/Application/Mappings.cs
src/Spd.Resource.Repository/Biz/BizRepository.cs
src/Spd.Resource.Repository/Biz/Mappings.cs
src/Spd.Resource.Repository/LicApp/LicAppRepository.cs
src/Spd.Resource.Repository/Licence/LicenceRepository.cs
src/Spd.Resource.Repository/LicenceFee/Mappings.cs
src/Spd.Resource.Repository/Org/Mappings.cs
src/Spd.Resource.Repository/Org/OrgRepository.cs
src/Spd.Resource.Repository/SharedMappingFuncs.cs
src/Spd.Utilities.Dynamics/DynamicsContextLookupHelpers.cs

- Optimize get servict type Id code

Optimize some service type code

---

src/Spd.Resource.Repository/Biz/BizRepository.cs
src/Spd.Resource.Repository/Biz/Contract.cs

Fix returned biz type by treating it as a nullable, avoiding assigning default values.

Fix returned biz type

---

src/Spd.Presentation.Licensing/Controllers/PaymentController.cs

biz payment

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

- deal DataServiceQueryException ex) when (ex.Response.StatusCode == 404)

deal DataServiceQueryException ex) when (ex.Response.StatusCode == 404)

---

src/Spd.Manager.Licence.UnitTest/BizLicAppValidationTest.cs
src/Spd.Manager.Licence/BizLicAppContract.cs
src/Spd.Manager.Licence/BizLicAppValidation.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs
src/Spd.Resource.Repository/BizLicApplication/Contract.cs
src/Spd.Resource.Repository/BizLicApplication/Mappings.cs

Add agreement field in business licence application upsert request. The modifications include:
- Add agreement field in business licence application upsert request, storing it in "application" entity
- Include condition before removing relationship between "application" and "licence"
- Plug request validator in business licence application submit "post" endpoint
- Refactor business licence application upsert request validations

Add agreement field in biz lic app upsert request

---

src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/BizLicensingControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs

Fix phone number returned value. The modification includes:
- Add missing mapping for applicant phone number
- Plug request validator in business licence application submit "post" endpoint

Fix phone number returned value

---

src/Spd.Resource.Repository.IntegrationTest/BizLicApplicationRepositoryTest.cs
src/Spd.Resource.Repository/BizLicApplication/Mappings.cs

Add date in consent and declaration

Add date in consent and declaration

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/model-desc.models.ts

SPDBT-2667 rename mcfd

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-log-in-options.component.ts

- added a sentence for PSSO applications "See your application progress in real time"

SPDBT-2554 - Add psso login text

---

src/Spd.Resource.Repository.IntegrationTest/BizLicApplicationRepositoryTest.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

Set default mailing and residential address in business licence application

Set default addresses in biz lic app service

---

src/Spd.Resource.Repository.IntegrationTest/ContactRepositoryTest.cs
src/Spd.Resource.Repository/Contact/ContactRepository.cs

- fix 2687 -Unauthorised User Licensing details not popping up for the first time user login.

fix 2687-Unauthorised User Licensing details not popping up for the first time user login.

---

src/Spd.Manager.Licence/ApplicantProfileValidation.cs
src/Spd.Manager.Licence/LicenceAppValidation.cs
src/Spd.Manager.Licence/PermitAppValidation.cs
src/Spd.Manager.Screening/ApplicationContract.cs
src/Spd.Presentation.Licensing/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/anonymous/permit-wizard-steps/step-permit-employer-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/anonymous/permit-wizard-steps/step-permit-mailing-address.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/anonymous/permit-wizard-steps/step-permit-summary-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/anonymous/permit-wizard-steps/step-permit-summary-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/anonymous/permit-wizard-steps/step-permit-summary-review-update-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/anonymous/worker-licence-wizard-steps/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile-personal-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-managers.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-bc-branch-edit.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-business-manager-edit.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-member-without-swl-edit.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-manager-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/step-components/common-contact-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/worker-licence-wizard-steps/step-worker-licence-mailing-address-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/directives/phone-number-transform.directive.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/pipes/phone-number.pipe.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/shared.module.ts

… directive
- phone number max length is 30, 
- remove phone mask, 
- use phone formatter directive and pipe

Phone Number updates

---

src/Spd.Manager.Screening/UserProfileManager.cs

- bug fixing: fe use orgName empty or null to check if we block user to go on using. So, we need to set orgName correctly.

fix wrong org code

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/payment.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/permit-wizard-authenticated-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/permit-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/worker-licence-wizard-authenticated-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/worker-licence-wizard-authenticated-replacement.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/worker-licence-wizard-authenticated-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-licence-wizard-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-licence-wizard-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-employees.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/steps-business-licence-controlling-members.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/steps-business-licence-review.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/business-licence-payment-cancel.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/business-licence-payment-error.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/business-licence-payment-fail.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/business-licence-payment-success.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/licence-payment-cancel.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/licence-payment-fail.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application-routing.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/Configurations/PaymentsConfiguration.cs
src/Spd.Presentation.Licensing/Controllers/PaymentController.cs
src/Spd.Presentation.Licensing/appsettings.json

- Business Licence payment
- Renewal updates

Business Licence payment

---

.github/workflows/docker-build-template.yml
.github/workflows/dynamics-helper-build.yml
.github/workflows/licensing-portal-build.yml
.github/workflows/screening-portal-build.yml

Fix for release builds

---

src/Spd.Manager.Licence.UnitTest/BizLicAppValidationTest.cs
src/Spd.Manager.Licence/BizLicAppBaseValidation.cs
src/Spd.Manager.Licence/BizLicAppValidation.cs
src/Spd.Manager.Licence/BizLicenceAppValidation.cs
src/Spd.Manager.Licence/LicenceAppValidation.cs

Create validator for biz renewal request. The modifications include additional test cases and refactoring of the related components.

Create validator for biz renewal request

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/licence-document-type-code.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/members-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/biz-licensing.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-controlling-members.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-employees.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.service.ts
src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs

- upload 'CorporateRegistryDocument' when controlling member data changes

Controlling member document

---

src/Spd.Manager.Licence/BizLicAppContract.cs
src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs
src/Spd.Resource.Repository.IntegrationTest/BizContactRepositoryTest.cs
src/Spd.Resource.Repository/BizContact/BizContactRepository.cs

- remove application id from controller for managing controlling member in biz level
- add code for managing controlling member in app level.

fix the issue when there is applicationid

---

src/Spd.Manager.Licence.UnitTest/BizLicenceAppManagerTest.cs
src/Spd.Manager.Licence/BizLicAppManager.cs

- get brand image for draft and incomplete applications

get brand image for draft and incomplete applications

---

src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs

Fix file upload route

---

src/Spd.Manager.Licence.UnitTest/BizProfileManagerTest.cs
src/Spd.Manager.Licence/BizProfileManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Resource.Repository/Biz/BizRepository.cs
src/Spd.Resource.Repository/Biz/Contract.cs
src/Spd.Resource.Repository/Biz/Mappings.cs

- spdbt-2725 (integrate bceid biz webservice into login process)

integrate bceid biz webservice into login process

---

src/Spd.Manager.Licence.UnitTest/BizLicenceAppManagerTest.cs
src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/BizLicensingControllerTest.cs

Implementation of business licence application replacement service

Implement biz lic app replacement service

---

src/Spd.Manager.Licence/SecurityWorkerAppManager.cs

- spdbt-2701-Refactor Update Personal licence. Needs to create a new full application with all doc copied

when update , make full application

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs
src/Spd.Resource.Repository/BizLicApplication/Mappings.cs

Adjust business licence application owner in partial save, assigning licensing CS team.

Adjust biz lic app owner

---

src/Spd.Presentation.Licensing/Controllers/PaymentController.cs
src/Spd.Presentation.Screening/Controllers/PaymentController.cs

- spdbt-2749: In the Business Licence payment return routes, add bizId.

align with screen org payment url

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs
src/Spd.Resource.Repository/BizLicApplication/Mappings.cs

-  comment out Private Investigator temporary: when Dynamics completes the schema change, redo this part.

comment out Private Investigator temporary

---

src/Spd.Manager.Licence.UnitTest/BizLicenceAppManagerTest.cs
src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Resource.Repository.IntegrationTest/BizRepositoryTest.cs
src/Spd.Resource.Repository/Biz/Contract.cs
src/Spd.Resource.Repository/Biz/Mappings.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

Adjust business licence application update service

Adjust biz lic app update service

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-submit-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/worker-licence-app-submit-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/licence.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-licence-wizard-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/steps-business-licence-review.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/step-components/common-alias-list.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/permit-application.service.ts

- SPDBT-2773 - fix creating alias
- SPDBT-2766 - add latest application id to update, renew and replace payload

Set latestApplicationId - fix alias bug

---

src/Spd.Manager.Printing/Documents/TransformationStrategies/Mappings.cs

- spdbt-2779(BCMP JSON - All Canadian Provinces need to be abbreviations)

province print

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

- forget to remove latestInactive for anonymous. This is to clean it up

remove latestInactive for anonymous

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/worker-licence-wizard-steps/step-worker-licence-summary-review-update-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/worker-licence-wizard-steps/step-worker-licence-update-fee.component.ts

SWL Update fixes

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/licence/api-licence-lookup-anonymous-licence-number-post.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/licence.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-first-time-user-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-licence-application-base.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/steps-business-licence-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/step-components/common-business-terms.component.ts

- SPDBT-2720 - handle first time login

Business licence - first time login

---

src/Spd.Manager.Printing/PrintingManager.cs
src/Spd.Presentation.Licensing/Controllers/PaymentController.cs
src/Spd.Presentation.Screening/Controllers/ApplicationController.cs
src/Spd.Utilities.FileStorage/FileStorageService.cs
src/Spd.Utilities.FileStorage/MainFileStorageService.cs
src/Spd.Utilities.FileStorage/ServiceExtensions.cs
src/Spd.Utilities.FileStorage/TransientFileStorageService.cs
src/Spd.Utilities.Payment/PaymentService.DirectRefund.cs

- Add logging for some exception.

add logging for exceptions

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/crrp-payment-success.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/payment-success.component.ts

- Hide close button for crrp payment success SPDBT-2804

Screening - Hide close button for crrp payment success

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/org-reg-duplicate-modal.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/step-components/agreement-of-terms.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-consent-to-crc.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-consent-to-release-of-info.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-declaration.component.ts

- SPDBT-2791 - move recaptcha to the consent page.

Screening - move recaptcha

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/services/auth-process.service.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/security-screening-portal/security-screening.component.ts

- Applicant portal - relative url issue

Applicant portal - relative url issue

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-first-time-user-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-licence-application-base.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/steps-business-licence-review.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/step-components/common-address.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application-routing.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.helper.ts

- Business Licensing - First time user - fix bug when user presses Back button during the process
- Update 'British Columbia' and 'Canada' validation to use a constant

Business Licensing - First time user

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

Add null verification for private investigator licence id

Add null verification for private investigator licence id

---

src/Spd.Presentation.Licensing/ClientApp/angular.json

- Remove basehref for licensing

Remove basehref

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-submit-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-upsert-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-profile-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-profile-update-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/private-investigator-swl-contact-info.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-manager.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-manager-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts

Biz lic manager integration

---

src/Spd.Presentation.Licensing/ClientApp/package.json
src/Spd.Presentation.Licensing/ClientApp/src/app/app.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/app.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/authentication.service.ts

- remove references to basehref

Licensing deploy issue

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/interceptors/auth-token.interceptor.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/anonymous/permit-wizard-steps/step-permit-criminal-history.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile-licence-criminal-history.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile-licence-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile-licence-police-background.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/user-profile/common-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/step-components/common-aliases.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/step-components/common-criminal-history.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/step-components/common-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/step-components/common-police-background.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/worker-licence-wizard-steps/step-worker-licence-criminal-history.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/worker-licence-wizard-steps/step-worker-licence-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/worker-licence-wizard-steps/step-worker-licence-police-background.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/biz-selection-modal.component.ts

- use dogs cost calculation bug
- create common components for mental health, police background and criminal history

Anonymous flow fixes

---

src/Spd.Presentation.Licensing/ClientApp/angular.json
src/Spd.Presentation.Licensing/ClientApp/src/app/app.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/app.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/authentication.service.ts

Licensing relative url

---

src/Spd.Manager.Licence.UnitTest/BizPortalUserManagerTest.cs
src/Spd.Manager.Licence/BizPortalUserContract.cs
src/Spd.Manager.Licence/BizPortalUserManager.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/BizPortalUserControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/BizPortalUserController.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

Implement get business portal user list endpoint. The modifications include:
- Creation of new Get business portal user list service (with necessary tests)
- Remove condition in contact query to get contact regardless of its state
- Get licence id from business contact when private investigator has to be unlinked

Implement get biz portal user list endpoint

---

src/Spd.Presentation.Licensing/Program.cs

add base_path

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application-routing.module.ts

- Rename module path licensing

Rename module path

---

src/Spd.Utilities.FileStorage/FileStorageService.cs

remove wrong log

---

src/Spd.Presentation.Licensing/ClientApp/src/app/app.component.ts

- get config after setting root url

Config relative issue

---

src/Spd.Resource.Repository/User/Mappings.cs
src/Spd.Resource.Repository/User/OrgUserRepository.cs

- spdbt-2649(fix tracking - save and update should not apply to all fields)
- this is a fix for the fix of 2649

a fix for the fix of 2649

---

src/Directory.Packages.props
src/Spd.Manager.Printing/Documents/TransformationStrategies/PersonalLicencePreviewTransformStrategy.cs
src/Spd.Manager.Printing/Spd.Manager.Printing.csproj

- use skiaSharp for resizing image as Drawing is not supported on non-windows platform

use skiaSharp for resizing image

---

src/Directory.Packages.props
src/Spd.Manager.Printing/Spd.Manager.Printing.csproj
src/Spd.Presentation.Dynamics/Spd.Presentation.Dynamics.csproj

cleanup
- Change SkiaSharp library for linux platform

Change library for linux version

---

src/Spd.Manager.Licence/LicenceAppManagerBase.cs
src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/biz-portal-user/api-business-biz-id-portal-users-get.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/biz-portal-user/api-business-biz-id-portal-users-user-id-put.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-portal-user-list-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-portal-user-update-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/biz-portal-user.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-managers.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-business-manager-edit.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/Controllers/BizPortalUserController.cs
src/Spd.Presentation.Licensing/Controllers/BizProfileController.cs

- Business managers - get/update

Business managers - get/update

---

tools/helm/charts/tools/templates/developing-release-pipeline.yaml
tools/helm/charts/tools/values.yaml

- get image directly from github

get image directly from github

---

src/Spd.Manager.Licence/BizPortalUserContract.cs
src/Spd.Resource.Repository.IntegrationTest/PortalUserRepositoryTest.cs
src/Spd.Resource.Repository/PortalUser/Contract.cs
src/Spd.Resource.Repository/PortalUser/Mappings.cs
src/Spd.Resource.Repository/PortalUser/PortalUserRepository.cs

Fix phone number in portal user PUT endpoint and include "IsActive" flag as part of portal user GET endpoint response

Fix phone number in portal user put endpoint

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/model-desc.models.ts

- SPDBT-2854 - service type label changes

SPDBT-2854 - service type label changes

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/anonymous/permit-wizard-steps/step-permit-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/licence-first-time-user-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-first-time-user-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/common-business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/step-business-licence-update-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/worker-licence-wizard-steps/step-worker-licence-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application-routing.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/common-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/permit-application.service.ts

- Business Licence - display terms during update flow

Business Licence - display terms during update flow

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-portal-user-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/business-managers.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/business/modal-business-manager-edit.component.ts

- Business Managers - active flag / email validation

Business Managers - active flag / email validation

---

src/Spd.Manager.Licence.UnitTest/BizLicAppValidationTest.cs
src/Spd.Manager.Licence/BizLicAppBaseValidation.cs
src/Spd.Manager.Licence/BizLicAppContract.cs
src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

Fix applicant contact information update when it is set to null in request

Fix applicant contact info update

---

src/Spd.Manager.Payment/PaymentManager.cs
src/Spd.Manager.Screening/ApplicationManager.Delegate.cs
src/Spd.Manager.Screening/ApplicationManager.cs
src/Spd.Manager.Screening/OrgManager.cs
src/Spd.Manager.Screening/OrgUserManager.cs
src/Spd.Manager.Screening/UserProfileManager.cs
src/Spd.Presentation.Screening/ClientApp/src/app/core/interceptors/error.interceptor.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/user-edit-modal.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/users.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/dialog-oops.component.ts
src/Spd.Presentation.Screening/Controllers/ApplicantController.cs
src/Spd.Presentation.Screening/Controllers/ApplicationController.cs
src/Spd.Presentation.Screening/Controllers/OrgRegistrationController.cs
src/Spd.Resource.Repository/Contact/ContactRepository.cs
src/Spd.Resource.Repository/Licence/LicenceRepository.cs
src/Spd.Resource.Repository/Org/OrgRepository.cs
src/Spd.Resource.Repository/Payment/PaymentRepository.cs
src/Spd.Resource.Repository/PortalUser/PortalUserRepository.cs
src/Spd.Resource.Repository/User/OrgUserRepository.cs

- Screening - show error messages properly

Screening - show error messages properly

---

src/Spd.Resource.Repository/User/OrgUserRepository.cs

fix user id

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/authenticated/permit-wizard-steps/steps-permit-updates-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/components/shared/step-components/common-criminal-history.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/licence-application/services/permit-application.service.ts

- Minor permit bug fixes - navigation, alignment

Minor permit bug fixes

---

src/Spd.Utilities.Dynamics/Connected Services/OData Service/ConnectedService.json

- fix errors in the app by regenerating OData

Regen OData

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/biz-portal-user/api-business-biz-id-portal-users-user-id-delete.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/biz-portal-user/api-business-biz-id-portal-users-user-id-get.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/biz-portal-user.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-managers.component.ts
src/Spd.Presentation.Licensing/Controllers/BizPortalUserController.cs

- Integrate business manager delete

[FE] Integrate business manager delete

---

src/Spd.Manager.Licence/BizPortalUserContract.cs
src/Spd.Manager.Licence/BizPortalUserManager.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/BizPortalUserControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs
src/Spd.Presentation.Licensing/Controllers/BizPortalUserController.cs
src/Spd.Presentation.Licensing/Controllers/BizProfileController.cs
src/Spd.Presentation.Licensing/UsersMiddleware.cs
src/Spd.Presentation.Screening/UsersMiddleware.cs
src/Spd.Resource.Repository.IntegrationTest/PortalUserRepositoryTest.cs
src/Spd.Resource.Repository/PortalUser/Contract.cs
src/Spd.Resource.Repository/PortalUser/PortalUserRepository.cs

- for spd-2759: add middleware, then add role claim to the login bceid user.
- add auth for bceid related endpoints for biz portal

biz portal user middle ware

---

src/Spd.Manager.Licence/ApplicantProfileContract.cs
src/Spd.Utilities.Dynamics/Connected Services/OData Service/ConnectedService.json

- changed type PoliceOfficerRoleEnum to PoliceOfficerRoleCode, in ApplicantProfileContract(because it is in manager layer)
- updated dynamic reference

changed type PoliceOfficerRoleEnum to PoliceOfficerRoleCode

---

src/Spd.Resource.Repository.IntegrationTest/BizLicApplicationRepositoryTest.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

- Null check exception returning for originalApp in CreateBizLicApplicationAsync()
- Adjusted test cases related to private investigator refactoring (BizLicApplicationRepositoryTest)

[SPDBT-2796] Adjusted test cases related to private investigator refactoring

---

src/Spd.Presentation.Licensing/ClientApp/package-lock.json
src/Spd.Presentation.Licensing/ClientApp/package.json
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/file-upload.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/directives/file-drag-n-drop.directive.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/shared.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/index.html

- replace file upload component

File upload replacement

---

src/Spd.Resource.Repository/PortalUser/Mappings.cs

fix biz manager invite link

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/invitation-link-organization.component.ts

- Screening - invitation org link bceid

Screening - invitation org link bceid

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/licence-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-licence-application-routing.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-application-base-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-application-base-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/scss/app.scss

…h the rest
- in permit and swl formgroup, rename address data to be consistent with the rest

Minor renaming

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/invitation-link-organization.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrpa-portal/crrpa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/org-registration.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/steps/step-four.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/steps/step-one.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/steps/step-three.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/pssoa-portal/pssoa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-organization-info.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-personal-info.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-terms-and-cond.component.ts

- SPDBT-2911 - CRC Personal Information page edit redirects to inappropriate page
- Fix navigation issues in the wizard in crrpa, pssoa, and org-registration

Screening navigation issues

---

src/Spd.Utilities.Printing/BCMailPlusSettings.cs
src/Spd.Utilities.Printing/ServiceExtensions.cs

- add option validator for bcMail Printing - spdbt-2919

add option validator for bcMail Printing

---

src/Spd.Resource.Repository/User/OrgUserRepository.cs

- Add protection code, if inivation is null, then just delete user.

deal with the situation that invitation is null, to delete user.

---

src/Spd.Resource.Repository/LicenceFee/LicenceFeeRepository.cs

-fix cache issue for licence fee

fix cache issue for licence fee

---

src/Spd.Manager.Licence/ControllingMemberCrcAppContract.cs

removed AccessCode
-edited fields and names in ControllingMemberCrcApp
-removed AccessCode

edited fields and names in ControllingMemberCrcApp

---

src/Spd.Manager.Licence/ControllingMemberCrcAppContract.cs
src/Spd.Manager.Licence/ControllingMemberCrcAppManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Contract.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Mappings.cs

- Added `ControllingMemberCrcAppManager` and Handle for `ControllingMemberCrcAppSubmitRequestCommand`
- Added Contract.cs and `CreateControllingMemberCrcAppCmd`
- Added mapping for `ControllingMemberCrcAppSubmitRequest `=> `CreateControllingMemberCrcAppCmd` (Manager.Licence)
-  Added Mappings.cs for repo layer (CreateCmd to `spd_contact` and `spd_application`)

Emad/controlling member crc manager, contract and mappings

---

src/Spd.Manager.Licence.UnitTest/BizLicenceAppManagerTest.cs
src/Spd.Manager.Licence/BizLicAppContract.cs
src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/BizLicAppValidation.cs
src/Spd.Resource.Repository.IntegrationTest/PersonLicApplicationRepositoryTest.cs
src/Spd.Resource.Repository/PersonLicApplication/Contract.cs
src/Spd.Resource.Repository/PersonLicApplication/PersonLicApplicationRepository.cs

- spdbt-2935 unauth new swl sole proprietor with biz

unauth new swl sole proprietor with biz

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-terms-and-cond.component.ts

SPDBT-2938 - Volunteer Service Requiring Payment 

---

src/Spd.Manager.Screening/OrgManager.cs

remove cache
- remove cache for org query

remove cache for org query

---

src/Spd.Manager.Licence/BizProfileContract.cs
src/Spd.Manager.Licence/Mappings.cs

- adding service types for biz list - as part of spdbt-2941

adding service types for biz list

---

tools/helm/charts/tools/templates/testing-release-pipeline.yaml

-add testing release pipeline - spdbt-2937

add testing release pipeline

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-submit-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-upsert-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-list-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/auth-user-bceid.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/controlling-member-login.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/shared/step-controlling-member-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/shared/step-controlling-member-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-fingerprints.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/scss/app.scss

- Update citizenship to use shared code for display of 'additional' section
- regen with latest backend
- SPDBT-2941 - complete but left as commented out

FE - code refactor and SPDBT-2941

---

src/Spd.Manager.Screening/ApplicationManager.cs
src/Spd.Resource.Repository/Application/ApplicationRepository.Application.cs
src/Spd.Resource.Repository/Application/Contract.Application.cs

-hotfix - jira-2947 confirm identity verified

confirm identity verified

---

src/Spd.Resource.Repository/ServiceTypes/ServiceTypeRepository.cs
src/Spd.Resource.Repository/WorkerLicenceCategory/WorkerLicenceCategoryRepository.cs

-[SPDBT-2914]Licensing - No Print preview generating in DEV & TEST environment

[SPDBT-2914]Licensing - No Print preview generating in DEV & TEST environment

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/alert.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/manual-submission-common.component.ts

- SPDBT-2953 not working when duplicate submission

SPDBT-2953 manual submission

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-contact-information.component.ts

- SPDBT-2948 - turn off name validation when name is readonly

SPDBT-2948 support single name

---

src/Spd.Manager.Screening/ApplicationContract.cs
src/Spd.Presentation.Screening/ClientApp/src/app/modules/psso-portal/components/delegate-add-modal.component.ts
src/Spd.Resource.Repository/PortalUser/PortalUserRepository.cs

- SPDBT-2951 - remove email validation for 'gov.bc.ca'

SPDBT-2951 - remove email validation for 'gov.bc.ca'

---

src/Spd.Manager.Licence/ControllingMemberCrcAppValidation.cs
src/Spd.Presentation.Licensing/Controllers/ControllingMemberCrcAppController.cs

-[SPDBT-2927] request validation
-[SPDBT-2929] captcha

controlling member validation + captcha ep

---

src/Spd.Manager.Licence/BizProfileManager.cs

- fix-do not update bizName if the trade-name from bceid is null.

fix-do not update bizName if the trade-name from bceid is null.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-licence-application-routing.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-application-base.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-swl-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-new-swl-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-business-address.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-expired.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/steps-business-licence-review.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/steps-business-licence-selection.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-expired.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-expired.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/file-upload.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/modal-biz-selection.component.ts

- Sole proprietor fixes
- SPDBT-2327 - update checklist text
- Change bizList to show the bizName

FE Sole proprietor fixes

---

src/Spd.Manager.Licence/ControllingMemberCrcAppContract.cs
src/Spd.Manager.Licence/ControllingMemberCrcAppManager.cs
src/Spd.Manager.Licence/LicenceAppDocumentManager.cs
src/Spd.Presentation.Licensing/Controllers/ControllingMemberCrcAppController.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Contract.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/ControllingMemberCrcRepository.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Mappings.cs

- endpoint for uploading file in cache
- added `LicenceAppManagerBase` as base class of `ControllingMemberCrcAppManager` (for upload purposes)
- verifying documents base on the conditions in confluence
- related refactoring (repository, mappings and req/resp records)

[SPDBT-2928] upload documents, controlling member crc app

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/controlling-member-crc-app/api-controlling-member-crc-applications-anonymous-files-post.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/controlling-member-crc-app/api-controlling-member-crc-applications-anonymous-key-code-post.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/controlling-member-crc-app-submit-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/licence-basic-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/licence-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/controlling-member-crc-app.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/controlling-member-crc.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/controlling-member-crc.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/licence-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/anonymous/controlling-member-wizard-anonymous-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/shared/step-controlling-member-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/shared/steps-controlling-member-background.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/shared/steps-controlling-member-citizenship-residency.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/shared/steps-controlling-member-personal-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/shared/steps-controlling-member-review.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-authenticated.component.ts

- controlling member crc integration
- various bug fixes
- SPDBT-2956 - fix display of photo

FE - controlling member crc integration and bug fixes

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/licence-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-update-received-success.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-anonymous-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-anonymous-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-anonymous-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-review-update-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/steps-permit-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-confirmation.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-authenticated-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-authenticated-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-step-components/steps-permit-review-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-update-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-update-received-success.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/permit-update-received-success.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/alert-update-or-renewal.component.ts

- use common summary functions - permit / swl

FE Common summary - permit / swl

---

src/Spd.Manager.Licence.UnitTest/ControllingMemberCrcAppManagerTest.cs

- utest for valid request, request without fingerproof

[SPDBT-2964]unit test controlling member crc app manager unit test

---

src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/SecurityWorkerAppManager.cs

- spdbt-2872: BE, When update and renew licence, get categories info from licence to do compare

renew update licence category

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/licence-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-access-code-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-active-swl-permit-licences.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/steps-worker-licence-selection.component.ts

- Update to use SWL Licence categories 
- show/hide sole proprietor question step when not a sole proprietor (in renew flow)

FE - licence categories 

---

src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/LicenceAppManagerBase.cs
src/Spd.Manager.Licence/SecurityWorkerAppContract.cs
src/Spd.Manager.Licence/SecurityWorkerAppManager.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs
src/Spd.Resource.Repository/BizLicApplication/Contract.cs
src/Spd.Resource.Repository/BizLicApplication/Mappings.cs
src/Spd.Resource.Repository/PersonLicApplication/Contract.cs
src/Spd.Resource.Repository/PersonLicApplication/Mappings.cs

1. in get bizLicApp and get swlLicApp, add other part app id to the response. (in bizLicAppResponse, we need to return swlAppId, in SwlAppResponse, we need to return bizLicAppId)
2. When user do submit for liz app, we need to update both swl and biz app status to payment pending or submitted.
3. For unauth sole proprietor swl, when user submit swl, do not commit the application.

spdbt 2936 - for sole proprietor

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts

- fix bug creating permit application

FE Permit bug

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/controlling-member-crc.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/licence-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/shared/step-controlling-member-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-swl-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/shared.module.ts

- swl and crc share citizenship

FE - crc citizenship

---

src/Spd.Manager.Licence/ApplicantProfileValidation.cs
src/Spd.Manager.Licence/BizLicAppBaseValidation.cs
src/Spd.Manager.Licence/BizProfileValidation.cs

- remove "firstname not empty" check for licensing

remove "firstname not empty" check for licensing

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-contact-information.component.ts
src/Spd.Presentation.Screening/Controllers/ApplicantController.cs

- set 'oneLegalName' to true when data is readonly

[SPDBT-2948] one legal name crrpa

---

src/Spd.Manager.Licence/BizMemberContract.cs

- add inviteId to verifyResponse

add inviteId to verifyResponse

---

src/Spd.Manager.Licence.UnitTest/ControllingMemberCrcAppManagerTest.cs
src/Spd.Manager.Licence/ControllingMemberCrcAppContract.cs
src/Spd.Manager.Licence/ControllingMemberCrcAppManager.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/ControllingMemberCrcRepository.cs

- added InviteId and get invite in create
- make Invite record status `completed` after application creation

[SPDBT-3008] cm-crc create with invite

---

src/Spd.Manager.Licence.UnitTest/ControllingMemberCrcAppManagerTest.cs
src/Spd.Manager.Licence/ControllingMemberCrcAppContract.cs
src/Spd.Manager.Licence/ControllingMemberCrcAppManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing/Controllers/ControllingMemberCrcAppController.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Contract.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/ControllingMemberCrcRepository.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Mappings.cs

- test save method, fix errors

fix cm-crc save and get

---

src/Spd.Manager.Licence.UnitTest/BizLicAppValidationTest.cs
src/Spd.Manager.Licence.UnitTest/BizLicenceAppManagerTest.cs
src/Spd.Manager.Licence/BizLicAppBaseValidation.cs
src/Spd.Manager.Licence/BizLicAppContract.cs
src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs

- spdbt-3030 : we need to remove controlling member from biz lic app payload as we separately deal with members

remove cm from biz app payload

---

src/Spd.Resource.Repository.IntegrationTest/BizContactRepositoryTest.cs

`ManageBizContactsAsync_WithExistingContacts_Correctly()`

[SPDBT-2716] fix test error ManageBizContactsAsync

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-consent-and-declaration.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-swl-permit-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-consent-and-declaration.component.ts

- SPDBT-1803, SPDBT-2028, SPDBT-2026

[SPDBT-1803], [SPDBT-2028], [SPDBT-2026] Term text updates

---

src/Spd.Manager.Payment/PaymentManager.cs

- spdbt-2985: Payment for sole Proprietor, set both applications paid.

add payment for biz and swl if it is sole proprietor app

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/manual-submission-common.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-request-add-common-modal.component.ts

- [SPDBT-2979] The message should only appear for Combined Criminal Check

[SPDBT-2979] The message should only appear for Combined Criminal Check

---

src/Spd.Manager.Licence/SharedContract.cs
src/Spd.Resource.Repository/PersonLicApplication/Contract.cs
src/Spd.Utilities.Dynamics/OptionSets.cs

- HairColourCode, HairColourEnum, HairColorOptionSet
- EyeColourCode, EyeColourEnum, EyeColorOptionSet

[SPDBT-3016] updated hair and eye colour enums

---

src/Spd.Resource.Repository/Application/ApplicationRepository.Statistics.cs

- [SPDBT-3017]Add payment pending statistics

[SPDBT-3017]Add payment pending statistics

---

src/Spd.Manager.Licence/BizMemberContract.cs
src/Spd.Manager.Licence/BizMemberManager.cs
src/Spd.Presentation.Licensing/Controllers/BizMembersController.cs

[SPDBT-3040] get non swl biz member endpoint

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/status-statistics-common.component.ts

- psso - hide 'complete - risk found'

[SPDBT-3043] psso - hide 'complete - risk found'

---

src/Spd.Resource.Repository.IntegrationTest/ControllingMemberCrcRepositoryTest.cs
src/Spd.Resource.Repository.IntegrationTest/ControllingMemberCrcRepositroyTest.cs
src/Spd.Resource.Repository.IntegrationTest/IntegrationTestSetup.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/ControllingMemberCrcRepository.cs

[SPDBT-2968] Intergration test for controlling member crc repository

---

src/Spd.Manager.Licence/BizMemberManager.cs

- invitation for wrong bizContact, change to a nicer response sentence

invitation for wrong bizContact, change to a nicer response sentence

---

src/Spd.Manager.Screening/ApplicationContract.cs

- [SPDBT-3058] be part- add Completed status for filtering

[SPDBT-3058] be part- add Completed status for filtering

---

src/Spd.Presentation.Screening/ClientApp/src/app/api/fn/payment/api-orgs-org-id-applications-application-id-payment-link-post.ts
src/Spd.Presentation.Screening/ClientApp/src/app/api/models/application-portal-status-code.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/model-desc.models.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-status-filter-common.component.ts

- PSSO Filter - Add 'Complete'

[SPDBT-3058] PSSO Filter - Add 'Complete'

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-consent-to-release-of-info.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-consent-to-release-pecrc.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/shared.module.ts

[SPDBT-2279] Pe Crc Consent Language

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrpa-portal/crrpa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/pssoa-portal/pssoa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/screening-application.model.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-personal-information.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-security-information.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-summary.component.ts

- PE-CRC Application should not show the VS category field
- PE-CRC application should not show the BC Govt Employee ID field

[SPDBT-3060] [SPDBT-3061] PE-CRC updates

---

src/Spd.Manager.Licence/ControllingMemberCrcAppManager.cs

changes are in New anonymous, and submit authenticated

[SPDBT-3051] change app status to payment pending after commit

---

src/Spd.Manager.Licence/ApplicantProfileManager.cs
src/Spd.Manager.Licence/Mappings.cs

let bcsc update addr

---

src/Spd.Resource.Repository/ControllingMemberInvite/ControllingMemberInviteRepository.cs

added InvitationTypeOptionSet.ControllingMemberCRCUpdate

fix-invite-type

---

src/Spd.Manager.Printing/Documents/TransformationStrategies/BizLicencePrintingTransformStrategy.cs

- biz licence printing needs to add conditions to printing body.

biz licence printing conditions

---

src/Spd.Resource.Repository/BizContact/BizContactRepository.cs

getting `FirstOrDefault()` from the `spd_businesscontact_spd_application` collection, then cancel it.

[SPDBT-3077] cancel and inactive spd_app when delete non-swl bizContact

---

src/Spd.Resource.Repository/BizContact/BizContactRepository.cs

- fix the delete bizContact bug: only remove the controlling member crc app

fix the delete bizContact bug: only remove the controlling member crc app

---

src/Spd.Manager.Licence/LicenceManager.cs
src/Spd.Resource.Repository/BizContact/Mappings.cs

- fix get licence
- fix renew biz licence, controlling member application status showing.

fix a small bug

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-statuses-common.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/status-statistics-common.component.ts
src/Spd.Presentation.Screening/ClientApp/src/index.html

[SPDBT-3100] Add refresh button

---

src/Spd.Resource.Repository/PersonLicApplication/PersonLicApplicationRepository.cs
src/Spd.Resource.Repository/SharedRepositoryFuncs.cs

-added `GetLicenceHolderContact` , modified personLicRepository to update expired licence's contact, instead of create in new request
-update the contact if new lic app request has expired licence(swl, permit)

[SPDBT-3092] update licence holder contact

---

src/Spd.Manager.Licence/LicenceManager.cs
src/Spd.Resource.Repository/Document/Contract.cs
src/Spd.Resource.Repository/Document/DocumentRepository.cs

-return the same set documents

return the same set documents

---

src/Directory.Packages.props
src/Spd.Utilities.LogonUser.UnitTest/Spd.Utilities.LogonUser.UnitTest.csproj
src/Spd.Utilities.LogonUser.UnitTest/UnitTest1.cs
src/Spd.Utilities.LogonUser/IPrincipalExtensions.cs
src/Spd.sln

- spdbt-3117(fix: if firstname and middlename are same, then the middle name is lost).

fix middleName issue

---

src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/SecurityWorkerAppManager.cs

update on renew

---

src/Spd.Manager.Screening/OrgRegistrationContract.cs
src/Spd.Presentation.Screening/ClientApp/src/app/api/models/anonymous-org-registration-create-request.ts
src/Spd.Presentation.Screening/ClientApp/src/app/api/models/configuration-response.ts
src/Spd.Presentation.Screening/ClientApp/src/app/api/models/org-registration-create-request.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/step-components/organization-information.component.ts
src/Spd.Resource.Repository/Registration/Contract.cs

- SPDBT-3116 remove 'hasPhoneOrEmail', update title

[SPDBT-3116] has phone or email

---

src/Spd.Manager.Screening/OrgRegistrationContract.cs
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/step-components/organization-information.component.ts
src/Spd.Presentation.Screening/Controllers/OrgRegistrationController.cs
src/Spd.Resource.Repository/Registration/Contract.cs
src/Spd.Resource.Repository/Registration/Mappings.cs

- spdbt-3131 (When Org do registration, we need also populate the legal name in spd_orgregistration entity.)

org register missing legal name

---

README.md
src/Spd.Presentation.Licensing/ClientApp/package-lock.json
src/Spd.Presentation.Screening/ClientApp/package-lock.json

fix angular compiling issue

---

src/Spd.Manager.Payment/Mappings.cs
src/Spd.Manager.Payment/PaymentManager.cs
src/Spd.Presentation.Licensing/Controllers/PaymentController.cs
src/Spd.Presentation.Screening/Controllers/PaymentController.cs
src/Spd.Resource.Repository/ApplicationInvite/Mappings.cs
src/Spd.Resource.Repository/Payment/Contract.cs
src/Spd.Resource.Repository/Payment/Mappings.cs
src/Spd.Resource.Repository/SharedMappingFuncs.cs

- spdbt-3133(Security Screening: Payment Confirmation Page shows email of the "Applicant" instead of the "Payee" Email address)

fix ui showing receipt email

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-consent-to-release-of-info.component.ts

- update consent language for pssoVs

[SPDBT-3134] update consent language for pssoVs

---

src/Spd.Manager.Licence/BizProfileContract.cs
src/Spd.Manager.Licence/BizProfileManager.cs

return bceid biz trade name

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-user-login-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-bc-branches.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-new-swl-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/modal-bc-branch-edit.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/steps-worker-licence-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/steps-worker-licence-review-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-consent-and-declaration.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/dialog.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/spd-header.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/wizard-footer.component.ts

[FE] SP bug fixes

---

src/Spd.Manager.Licence/BizLicAppContract.cs
src/Spd.Manager.Licence/BizProfileManager.cs
src/Spd.Manager.Licence/BizProfileValidation.cs
src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs
src/Spd.Resource.Repository/BizLicApplication/Contract.cs
src/Spd.Resource.Repository/SharedRepositoryFuncs.cs

- add validation for max phone number length
- add submittedby for sbl

spdbt-3144 and add submitted by

---

src/Spd.Presentation.Licensing/ClientApp/package-lock.json

[FE] npm update

---

src/Spd.Manager.Screening/ApplicationContract.cs
src/Spd.Resource.Repository/Application/ApplicationRepository.Statistics.cs
src/Spd.Resource.Repository/Application/Contract.Application.cs

- [SPDBT-3120]BE: add Complete statistics

[SPDBT-3120]BE: add Complete statistics

---

src/Spd.Manager.Screening/ApplicationContract.cs
src/Spd.Resource.Repository/Application/ApplicationRepository.Statistics.cs
src/Spd.Resource.Repository/Application/Contract.Application.cs

- spdbt-3120 update to completed

spdbt-3120 update to completed

---

src/Spd.Presentation.Licensing/ClientApp/package-lock.json

npm update

---

src/Spd.Manager.Licence/BizLicAppValidation.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

- biz app link spd_organization to account
- copy manager info to app 
- if applicant is manager, copy manager info to applicant info
- allow max 10 insurance documents

Spdbt-3145

---

src/Spd.Presentation.Screening/ClientApp/package-lock.json
src/Spd.Presentation.Screening/ClientApp/package.json
src/Spd.Presentation.Screening/ClientApp/src/app/core/services/util.service.ts

- Screening - update jwt_decode

[FE] Screening - update jwt_decode

---

src/Spd.Presentation.Screening/ClientApp/src/app/api/models/anonymous-org-registration-create-request.ts
src/Spd.Presentation.Screening/ClientApp/src/app/api/models/application-statistics-response.ts
src/Spd.Presentation.Screening/ClientApp/src/app/api/models/org-registration-create-request.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/application-portal-statistics-type.model.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/code-desc-types.models.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/model-desc.models.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/status-statistics-common.component.ts

- [SPDBT-3120] add completed status

[SPDBT-3120] add completed status

---

src/Spd.Presentation.Licensing/Controllers/LicenceAppDocumentController.cs

fix auth issue

---

src/Spd.Presentation.Licensing/Controllers/LicenceAppDocumentController.cs
src/Spd.Presentation.Licensing/Spd.Presentation.Licensing.csproj
src/Spd.Presentation.Screening/Controllers/ApplicantController.cs
src/Spd.Presentation.Screening/Controllers/ApplicationController.cs
src/Spd.Presentation.Screening/Spd.Presentation.Screening.csproj

-spdbt-3146(ook up the file virus scan service with our screening and licensing app.)

file scan for screening and licensing

---

src/Spd.Presentation.Licensing/ClientApp/.prettierrc.json
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/controlling-member-crc.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-new.component.ts

- update document api endpoints

[FE] update document api endpoints

---

src/Spd.Presentation.Licensing/Controllers/ConfigurationController.cs

-spdbt-3161 add env for configuration

add env for configuration

---

src/Spd.Presentation.Licensing.UnitTest/Controller/BizLicensingControllerTest.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/LicenceAppDocumentControllerTest.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/PermitControllerTest.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/SecurityWorkerLicensingControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/ApplicantProfileController.cs
src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs
src/Spd.Presentation.Licensing/Controllers/ControllingMemberCrcAppController.cs
src/Spd.Presentation.Licensing/Controllers/PermitController.cs
src/Spd.Presentation.Licensing/Controllers/SecurityWorkerLicensingController.cs

removed older document endpoints

---

src/Spd.Manager.Licence.UnitTest/LicenceManagerTest.cs
src/Spd.Manager.Licence/LicenceContract.cs
src/Spd.Manager.Licence/LicenceManager.cs
src/Spd.Resource.Repository/Biz/BizRepository.cs
src/Spd.Resource.Repository/Biz/Contract.cs
src/Spd.Resource.Repository/Licence/Contract.cs
src/Spd.Resource.Repository/Licence/LicenceRepository.cs
src/Spd.Resource.Repository/Licence/Mappings.cs
src/Spd.Resource.Repository/SharedMappingFuncs.cs

- add linkedLicenceId and linkedExpiryDate to licence endpoint to indicate if it is created from sole proprietor flow.

add data to licence endpoint to indicate if it is created from sole proprietor flow.

---

src/Spd.Resource.Repository/Licence/Mappings.cs

fix biztype

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/config.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/captcha-v2.component.ts

[FE] fix recaptcha

---

src/Spd.Resource.Repository/Licence/Mappings.cs
src/Spd.Utilities.FileStorage/FileStorageService.cs

- fix spdbt-3170 : Prod issue: Request headers must contain only ASCII characters. Upload file with filename contains non-ascii chars.

fix spdbt-3170 (Prod issue: Request headers must contain only ASCII characters.)

---

src/Spd.Manager.Licence/LicenceManager.cs

- add condition to make response cleaner - getLicence for sole proprietor

add condition to make response cleaner

---

src/Spd.Manager.Licence/BizLicAppContract.cs
src/Spd.Manager.Licence/LicenceAppManagerBase.cs
src/Spd.Manager.Licence/LicenceManager.cs
src/Spd.Resource.Repository/Licence/LicenceRepository.cs

- spdbt-3177 : fix issue for get sole proprietor swl lic photo

fix issue for get sole proprietor swl lic photo

---

src/Spd.Manager.Licence/Mappings.cs

conditional mapping to do not return soleProprietorSwlContactInfo, phone and email if the biz type is not sole proprietor

[SPDBT-3166] conditional mapping for soleProprietorSwl info

---

src/Spd.Resource.Repository/Biz/BizRepository.cs
src/Spd.Resource.Repository/Biz/Mappings.cs

- Licensing - BCeID issues logging into SBL with new bceid, got exception for accounted cannot not empty.

spdbt-3175-Licensing - BCeID issues logging into SBL

---

src/Spd.Manager.Licence/BizLicAppManager.cs

fix move files for sp

---

src/Spd.Resource.Repository/User/OrgUserRepository.cs

- [SPDBT-3180] screening prod: portal user invitation, compare orgGuid with users org guid should be case insensitive.

[SPDBT-3180] screening prod: portal user invitation, compare orgGuid with users org guid should be case insensitive.

---

src/Spd.Manager.Licence/SecurityWorkerAppManager.cs

-spdbt-3183( renew, sp, commit later)

renew, sp, commit later

---

src/Spd.Manager.Licence.UnitTest/BizLicAppValidationTest.cs
src/Spd.Manager.Licence.UnitTest/BizLicenceAppManagerTest.cs
src/Spd.Manager.Licence.UnitTest/BizPortalUserManagerTest.cs
src/Spd.Manager.Licence.UnitTest/BizProfileValidationTest.cs
src/Spd.Manager.Licence.UnitTest/ControllingMemberCrcAppManagerTest.cs
src/Spd.Manager.Licence.UnitTest/LicenceManagerTest.cs
src/Spd.Manager.Licence.UnitTest/SecurityWorkerAppManagerTest.cs
src/Spd.Manager.Licence/BizLicAppValidation.cs

fixed licence manager uTest errors, modified mock repositories, modified assertions to meet current validators

[SPDBT-3172] fix Spd.Manager.Licence.UnitTest

---

src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/LicenceAppManagerBase.cs
src/Spd.Resource.Repository/LicApp/Contract.cs
src/Spd.Resource.Repository/LicApp/LicAppRepository.cs

- spdbt-3149(SP, when submitting biz app, adjust swl term to be the same as biz app.)

update term for swl

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/validators/form-control.validators.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/address.component.ts

[FE] bc address bug

---

src/Spd.Manager.Licence/LicenceManager.cs

- return licence in preview, active and expired status

return preview licence

---

src/Spd.Manager.Licence.UnitTest/PermitAppManagerTest.cs
src/Spd.Manager.Licence/PermitAppManager.cs

- licrepo.QueryAsync => GetAsync
- extract methods for reprint and clean old files

[SPDBT-3084]  Refactor Permit Update logic

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/services/config.service.ts
src/Spd.Utilities.LogonUser/ServiceExtensionAuthentication.cs

change bscs to login with css based

---

src/Spd.Presentation.Licensing/UsersMiddleware.cs
src/Spd.Presentation.Screening/UsersMiddleware.cs

- [SPDBT-3126] Change BCSC login to use CSS based

[SPDBT-3126] Change BCSC login to use CSS based

---

src/Spd.Resource.Repository.IntegrationTest/AddressRepositoryTest.cs
src/Spd.Resource.Repository.IntegrationTest/BizContactRepositoryTest.cs
src/Spd.Resource.Repository.IntegrationTest/BizLicApplicationRepositoryTest.cs
src/Spd.Resource.Repository.IntegrationTest/BizRepositoryTest.cs
src/Spd.Resource.Repository.IntegrationTest/ContactRepositoryTest.cs
src/Spd.Resource.Repository/PersonLicApplication/PersonLicApplicationRepository.cs

[SPDBT-3209] fixed Repository integration tests

---

src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/PermitAppManager.cs
src/Spd.Manager.Licence/SecurityWorkerAppManager.cs

- spdbt-3216(renew should be allowed on the last day )

fix renew on the last day

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/manual-submission-common.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-personal-information.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-security-information.component.ts

- SPDBT-3207 - sex mandatory
- Made 'contractedCompanyName' max length same as in Manual Submission

[SPDBT-3207] - sex mandatory

---

src/Spd.Resource.Repository/Application/ApplicationRepository.Application.cs
src/Spd.Utilities.Dynamics/OptionSets.cs

- SPDBT-3220(Automated Screening Sharing always creating with Risk Assessment)

SPDBT-3220(Automated Screening Sharing always creating with Risk Assessment)

---

src/Spd.Resource.Repository/Application/ApplicationRepository.Application.cs

- [SPDBT-3220] Set isSystemGenerated to true for clearance access

[SPDBT-3220] Set isSystemGenerated to true for clearance access

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-controlling-members.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-swl-permit-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-business-terms.component.ts

- SPDBT-1803 - term wording updates
- SPDBT-3208 - controlling member invite error

[FE] Bug fixes

---

src/Spd.Manager.Licence/ApplicantProfileValidation.cs
src/Spd.Manager.Licence/ControllingMemberCrcAppValidation.cs
src/Spd.Manager.Licence/LicenceAppValidation.cs
src/Spd.Manager.Screening/ApplicationContract.cs

- spdbt-3200: Add validation for birth date.

add validation for birthdate

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-personal-information-new-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-personal-information-renew-update-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-swl-citizenship.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/manual-submission-common.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-personal-information.component.ts

- SPDBT-3200 - add min date validation to all date fields - birth dates, expiry dates, etc

[SPDBT-3200] FE - min date validation

---

src/Spd.Manager.Licence/BizLicAppManager.cs

- [spdbt-3229] - link renew sp biz licence app and swl lic app

[spdbt-3229] - link renew sp biz licence app and swl lic app

---

src/Spd.Manager.Licence/BizLicAppContract.cs
src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Presentation.Licensing/Controllers/LicenceAppController.cs
src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs
src/Spd.Resource.Repository/BizLicApplication/Contract.cs

when application is not type of new and the status is draft or incomplete, user can cancel it

[SPDBT-3227] cancel application endpoint.

---

src/Spd.Manager.Licence/ApplicantProfileValidation.cs
src/Spd.Manager.Licence/ControllingMemberCrcAppValidation.cs
src/Spd.Manager.Licence/LicenceAppValidation.cs
src/Spd.Manager.Licence/PermitAppValidation.cs
src/Spd.Manager.Licence/SecurityWorkerAppValidation.cs
src/Spd.Resource.Repository/Document/DocumentRepository.cs

expiry date and date of birth min value validation

[SPDBT-3235] expiry date and date of birth min value validation

---

src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/PermitControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/PermitController.cs
src/Spd.Resource.Repository/Licence/Mappings.cs

- fix permit update mapping issue - if null, update to empty

fix permit update mapping issue

---

src/Spd.Manager.Payment/PaymentManager.cs
src/Spd.Tests/Integration/IntegrationTestFixture.cs
src/Spd.Tests/Integration/Utilities/Payment/PaymentServiceTests.cs
src/Spd.Tests/Spd.Tests.csproj
src/Spd.Utilities.Payment/Contract.cs
src/Spd.Utilities.Payment/PayBCSettings.cs
src/Spd.Utilities.Payment/PaymentService.DirectRefund.cs
src/Spd.Utilities.Payment/PaymentService.Invoice.cs
src/Spd.Utilities.Payment/TokenProviders/BasicSecurityTokenProvider.cs
src/Spd.Utilities.Payment/TokenProviders/BearerSecurityTokenProvider.cs
src/Spd.Utilities.Payment/TokenProviders/SecurityTokenProvider.cs

- refund config for licensing and screening

refund config for licensing and screening

---

src/Spd.Manager.Payment/PaymentManager.cs

- [SPDBT-3232] PayBC DirectPay Payment URL: add ApplicationId in Description

[SPDBT-3232] PayBC DirectPay Payment URL: add ApplicationId in Description - screening part

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/landing.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-category-amoured-car-guard.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-business-address.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-checklist-renew.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-controlling-members.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-liability.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/step-controlling-member-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/step-controlling-member-checklist-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-swl-permit-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/licence-category-armoured-car-guard.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/access-denied.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-business-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-personal-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-police-background.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/spd-footer.component.ts

- update terms text
- update invalid link
- move urls to constants file

[SPDBT-1803], [SPDBT-1575] terms and link

---

src/Spd.Manager.Payment/Contract.cs
src/Spd.Presentation.Licensing/Controllers/PaymentController.cs
src/Spd.Presentation.Screening/Controllers/PaymentController.cs
src/Spd.Utilities.LogonUser/IPrincipalExtensions.cs

-spdbt-3232(set payment description from be with case id)

set payment description from be

---

src/Spd.Manager.Licence/ControllingMemberCrcAppManager.cs
src/Spd.Manager.Licence/LicenceAppManagerBase.cs
src/Spd.Resource.Repository/BizLicApplication/Mappings.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Mappings.cs
src/Spd.Resource.Repository/LicApp/LicAppRepository.cs
src/Spd.Resource.Repository/PersonLicApplication/Mappings.cs
src/Spd.Resource.Repository/SharedMappingFuncs.cs

- fix licence fee for cm crc
- fix date signed

fixing 3296 -Licensing - Controlling Member CRC Application

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/applicant-profile-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/applicant-update-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-step-components/step-permit-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-step-components/steps-permit-identification-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/user-profile-components/common-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/steps-worker-licence-identification-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/permit-wizard-step-components/step-permit-physical-characteristics.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-physical-characteristics.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/personal-licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-physical-characteristics.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/shared.module.ts

- move characteristics into profile

[SPDBT-3278] move characteristics into profile

---

src/Spd.Presentation.Licensing/Controllers/PaymentController.cs
src/Spd.Presentation.Screening/Controllers/PaymentController.cs

- add log for missing payment scenario

add log for missing payment scenario

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/user-profile-components/common-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-physical-characteristics.component.ts

- fix checking of characteristics validity

SWL Replacement bug

---

src/Spd.Manager.Licence/BizLicAppBaseValidation.cs

- remove validation for the name for pi

fix: remove validation for the name for pi

---

src/Spd.Resource.Repository/Org/Contract.cs

- fix max authorized contact number

fix max authorized contact number

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/auth-process.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/authentication.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/config.service.ts

- fix check for 'identity_provider'

[FE] fix check for 'identity_provider'

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-application-base.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-payment-cancel.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-payment-fail.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-payment-success.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-new-swl-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-renewal-swl-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-replacement.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/licence-application-base-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-swl-permit-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-payment-cancel-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-payment-cancel.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-payment-fail-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-payment-fail.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-payment-success-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-payment-success.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/file-upload.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-business-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/payment-fail.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/payment-success.component.ts

- [SPDBT-3325] back button issues

[SPDBT-3325] back button issues

---

src/Directory.Packages.props
src/Spd.Engine.Validation/Contract.cs
src/Spd.Manager.Licence/BizProfileValidation.cs
src/Spd.Presentation.Licensing/Swagger/ApiFilters/LicenceAppDocumentPostparamTypesFilter.cs
src/Spd.Presentation.Licensing/Swagger/SwaggerServiceExtension.cs

- fix file upload swagger
- fix pr for upgrading validation

fix swagger

---

src/Spd.Presentation.Licensing/Swagger/ApiFilters/LicenceAppDocumentPostparamTypesFilter.cs

- change swagger generated to be TypeCode, not string

change to type

---

src/Directory.Packages.props

- fix login failure caused by upgrading

fix login failure caused by upgrading

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/licence-app-document/api-licence-application-documents-anonymous-files-post.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/licence-app-document/api-licence-application-documents-files-post.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/fn/licence-app-document/api-licence-application-documents-licence-app-id-files-post.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/services/licence-app-document.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/controlling-member-crc.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts

[FE] swagger updates

---

src/Spd.Manager.Licence/LicenceAppManagerBase.cs
src/Spd.Manager.Payment/PaymentManager.cs
src/Spd.Resource.Repository/Document/Mappings.cs

- spdbt-3349
- remove set children app paid
- fix get document for latest set issue

biz app fix

---

src/Spd.Presentation.Licensing/Controllers/PaymentController.cs
src/Spd.Presentation.Screening/Controllers/PaymentController.cs
src/Spd.Resource.Repository/Payment/PaymentRepository.cs

upgrade for payment report

---

.github/dependabot.yml

- change dependabot to do monthly check every month for fe.

change dependabot to do monthly check every month for fe.

---

src/Spd.Manager.Payment/Contract.cs

remove duplicate definition

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-controlling-members.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-step-components/step-permit-summary-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-step-components/step-permit-summary-review-update-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-update-authenticated.component.ts

- do not allow update invitation when application exists
- SPDBT-3372

[FE] SPDBT-3372 & update invitation change

---

src/Spd.Manager.Licence/ApplicantProfileManager.cs

- [SPDBT-3370] SWL Profile document saving bug

[SPDBT-3370] SWL Profile document saving bug

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-submit-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/biz-lic-app-upsert-request.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/payment-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-applications-list-current.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/modal-lookup-by-licence-number.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/scss/_material-overrides.scss

- SPDBT-3214 - update error message
- SPDBT-3883 - category bug - display for update flow
- SPDBT-3387 - add reference to swl for BL/SP

[FE] various fixes

---

src/Spd.Resource.Repository/BizLicApplication/Mappings.cs
src/Spd.Utilities.Dynamics/ODataClientHandler.cs

- [SPDBT-3390] Enable null update

[SPDBT-3390] Enable null update

---

src/Spd.Resource.Repository/Document/DocumentRepository.cs

- [SPDBT-3389] Fix bug for file copying

[SPDBT-3389] Fix bug for file copying

---

src/Spd.Utilities.Dynamics/ODataClientHandler.cs

- SPDBT-3390: BL - SP - appl saving incorrect dog data

[SPDBT-3390] BL - SP - appl saving incorrect dog data

---

src/Spd.Manager.FinanceReconciliation/Contract.cs
src/Spd.Manager.FinanceReconciliation/FinancialReconciliationManager.cs
src/Spd.Manager.FinanceReconciliation/Spd.Manager.FinanceReconciliation.csproj
src/Spd.Presentation.Dynamics/Controllers/FinancialReconciliationController.cs
src/Spd.Presentation.Dynamics/Controllers/PaymentController.cs
src/Spd.Presentation.Dynamics/Spd.Presentation.Dynamics.csproj
src/Spd.sln

- dynamics helper financial reconciliation framework: add some basic code for financial reconciliation, no real effective code will be used.

dynamics helper financial reconciliation framework

---

src/Spd.Manager.Screening/ApplicationMappings.cs

- [SPDBT-3404] Screening: SPARC consent field should also be "Yes" for generic upload & organization submitted applications

[SPDBT-3404] Screening: SPARC consent field should also be "Yes" for generic upload & organization submitted applications

---

src/Spd.Manager.Licence/BizMemberContract.cs
src/Spd.Manager.Licence/BizMemberManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Contract.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Mappings.cs
src/Spd.Resource.Repository/SharedMappingFuncs.cs

- [SPDBT-3352] Licensing - Create Controlling Member CRC shell Application when No Email is provided - Backend

[SPDBT-3352] Licensing - Create Controlling Member CRC shell Application when No Email is provided

---

src/Spd.Manager.Licence.UnitTest/BizLicenceAppManagerTest.cs
src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/PermitAppManager.cs
src/Spd.Manager.Licence/SecurityWorkerAppManager.cs
src/Spd.Resource.Repository/Application/ApplicationRepository.Clearance.cs
src/Spd.Utilities.Shared/Tools/DateOnlyHelper.cs

- [SPDBT-3376] Licensing - SWL Renewal Issue timezone issue

[SPDBT-3376] Licensing - SWL Renewal Issue timezone issue

---

src/Directory.Packages.props
src/Spd.Utilities.Shared/Spd.Utilities.Shared.csproj
src/Spd.Utilities.Shared/Tools/DateOnlyHelper.cs

-Support cross platform timezone converting

Cross platform timezone changing

---

src/Spd.Manager.Licence/LicenceContract.cs
src/Spd.Resource.Repository/Licence/Contract.cs
src/Spd.Resource.Repository/Licence/Mappings.cs

- add BizLegalName to biz search

add BizLegalName to biz search

---

src/Spd.Manager.Licence/LicenceContract.cs
src/Spd.Resource.Repository/Licence/Contract.cs
src/Spd.Resource.Repository/Licence/Mappings.cs
src/Spd.Resource.Repository/PersonLicApplication/PersonLicApplicationRepository.cs

- [spdbt-3402] expired licence lookup changes

[spdbt-3402] expired licence lookup changes

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/security-licence-status-verification/components/security-licence-status-verification-sbl.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/security-licence-status-verification/components/security-licence-status-verification-swl.component.ts

[FE] add search by one name only

---

src/Spd.Manager.Licence/BizLicAppContract.cs

-fix ApplicantIsBizManager is null issue

fix ApplicantIsBizManager is null issue

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/licence-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/security-licence-status-verification/components/security-licence-status-verification-sbl.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/security-licence-status-verification/components/security-licence-status-verification-swl.component.ts

- SPDBT-3277 fix losing of photo
- Fix BL PI validation bug

[FE] SPDBT-3277 bug fixes

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/step-components/vulnerable-sector-question.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/org-registration-portal/steps/step-one.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/manual-submission-common.component.ts

- [SPDBT-3434] make checkbox mandatory
- [SPDBT-3427] fix employee/volunteer wording

[SPDBT-3427] [SPDBT-3434] 

---

src/Spd.Manager.Licence/ControllingMemberCrcAppValidation.cs

- SPDBT-3446 : cm app validation

licensing: fix 3446 (cm app validation)

---

src/Spd.Manager.Licence/SharedContract.cs
src/Spd.Resource.Repository/SharedContract.cs
src/Spd.Resource.Repository/SharedMappingFuncs.cs

- [SPDBT-3452] Police Officer code : add None and fix mapping

[SPDBT-3452] Police Officer code : add None and fix mapping

---

src/Spd.Manager.Licence/PermitAppManager.cs

- [SPDBT-3445] fix update lost permit photo

[SPDBT-3445] fix update lost permit photo

---

src/Spd.Manager.Licence/ControllingMemberCrcAppValidation.cs

- [SPDBT-3446]Controlling Member validation - reorg cm validation

[SPDBT-3446]Controlling Member validation - reorg cm validation

---

src/Spd.Resource.Repository/Document/DocumentRepository.cs
src/Spd.Resource.Repository/Document/Mappings.cs

- [SPDBT-3262] Permit anonymous update - added document lost

[SPDBT-3262] Permit anonymous update - added document lost

---

src/Spd.Presentation.Licensing/ClientApp/package-lock.json
src/Spd.Presentation.Licensing/ClientApp/package.json
src/Spd.Presentation.Screening/ClientApp/package-lock.json
src/Spd.Presentation.Screening/ClientApp/package.json

angular-oauth2-oidc v19

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

-to update object and save changes. it is very strange that it is not saved before.

add another save changes to ensure the app got updated.

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

- fix reading pi for biz licence

fix reading pi

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

- [SPDBT-3470] Applicant SWL Number not set

[SPDBT-3470] Applicant SWL Number not set

---

src/Spd.Manager.Licence/LicenceAppManagerBase.cs

- [SPDBT-3463] Simultaneous Business Licence - swl licence fee

[SPDBT-3463] Simultaneous Business Licence - swl licence fee

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/alert.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/modal-lookup-by-licence-number.component.ts

- SPDBT-3500 Fix licence lookup bug
- Move info text above the search field. 
- Make alert color/border consistent

[FE] SPDBT-3500 Fix licence lookup bug

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs
src/Spd.Resource.Repository/BizLicApplication/Contract.cs

- [SPDBT-3468] Controlling Member Employee getting duplicated

[SPDBT-3468] Controlling Member Employee getting duplicated

---

src/Spd.Resource.Repository/BizLicApplication/BizLicApplicationRepository.cs

-[SPDBT-3468] duplicate PI info when biz licence does update

[SPDBT-3468] duplicate PI info when biz licence does update

---

src/Spd.Manager.Licence/LicenceAppManagerBase.cs
src/Spd.Manager.Licence/PermitAppManager.cs

- remove "previousDocument must be within previous application" cretieria

remove "previousDocument must be within previous application" cretieria

---

src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/captcha-v2.component.ts

[FE] remove dev sitekey

---

src/Spd.Resource.Repository/Biz/BizRepository.cs
src/Spd.Resource.Repository/BizContact/BizContactRepository.cs

- [SPDBT-3528] sole proprietor: swl licence in profile needs to be added as controlling member biz contact

[SPDBT-3528] sole proprietor: swl licence in profile needs to be added as controlling member biz contact

---

src/Spd.Resource.Repository/Biz/BizRepository.cs

fix put profile for biz

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-confirmation.component.ts

[SPDBT-3544] SonarQube fixes

---

src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/file-upload.component.ts

- objectUrl check domain is valid

objectUrl check domain is valid

---

src/Spd.Presentation.Dynamics/Controllers/FileStorageController.cs
src/Spd.Resource.Repository/SharedMappingFuncs.cs

- [SPDBT-3546] fix-sonarcube: add timeout for RegEx and review max fileSize.

[SPDBT-3546] fix-sonarcube: add timeout for RegEx and review max fileSize.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/file-upload.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/file-upload.component.ts

- [SPDBT-3542] Fix re-attachment of the same document - Screening and Licensing

[SPDBT-3542] Fix re-attachment of the same document

---

src/Spd.Manager.Licence/BizLicAppManager.cs

[SPDBT-3550]biz licence renew: fix previousdocument checking, no need to filter based on if they are from latest application.

[SPDBT-3550]biz licence renew: fix previousdocument checking, no need to filter based on if they are from latest application.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-photograph-of-yourself.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-fingerprints.component.ts

- SPDBT-3495
- Plus, fix bug calculating fee

SPDBT-3495 - usability photo

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-consent-and-declaration.component.ts

- SPDBT-3505 - usability consent

SPDBT-3505 - usability consent

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-access-code-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-user-applications.component.ts

- Force expired PI licence to be reselected.

[FE] Force expired PI licence to be reselected.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-managers.component.ts

[SPDBT-3519] add tooltips

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/user-edit-modal.component.ts

- User Mgmt - missing required validation msg

[SCREENING] User Mgmt - missing required validation msg

---

src/Spd.Manager.Licence/BizPortalUserManager.cs
src/Spd.Manager.Screening/OrgUserManager.cs

- [SPDBT-3560] prod-portal user delete: remove the max number checking for delete portal user.

[SPDBT-3560] prod-portal user delete: remove the max number checking for delete portal user.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-managers.component.ts

SPDBT-3519 fix alignment

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/users.component.ts
src/Spd.Resource.Repository/Biz/Contract.cs
src/Spd.Resource.Repository/Biz/Mappings.cs
src/Spd.Resource.Repository/Org/Contract.cs
src/Spd.Resource.Repository/Org/Mappings.cs

- [SPDBT-3570] Screening: Org max no of authorized contact means only ac, not include primary AC. OS Be needs to accomandate dynamics setting.

[SPDBT-3570] Screening: Org max no of authorized contact means only ac, not include primary AC. Be needs to accomandate dynamics setting.

---

src/Spd.Resource.Repository/Biz/Contract.cs
src/Spd.Resource.Repository/Org/Contract.cs

- fix a bug for biz manager count: it does not reflect what has changed

fix a bug for biz manager count

---

src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppValidation.cs

- [SPDBT-3555]GDSD view model update

[SPDBT-3555]GDSD view model update

---

src/Spd.Manager.Shared/Contract.cs
src/Spd.Resource.Repository/SharedContract.cs
src/Spd.Utilities.Dynamics/DynamicsContextLookupHelpers.cs

add gdsd service type

---

src/Spd.Manager.Licence.UnitTest/GDSDAppValidationTest.cs
src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppValidation.cs
src/Spd.Presentation.Licensing/Controllers/GDSDLicensingController.cs

Add gdsd validation

---

src/Spd.Manager.Licence.UnitTest/GDSDAppValidationTest.cs
src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppValidation.cs

- Add loop training and validator and unit tests

Add loop training and validator

---

src/Spd.Manager.Licence.UnitTest/GDSDAppValidationTest.cs
src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppValidation.cs

- adjust the gdsd contract according to the review

adjust the gdsd contract according to the review

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-controlling-members-and-employees.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-controlling-members.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-employees.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/modal-member-without-swl-edit.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-employees.component.ts

- SPDBT-3499 - expired licence usability 
- SPDBT-3507 - controlling member usability

SPDBT-3499, SPDBT-3507 usability updates

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/gdsd-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/gdsd-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/anonymous/gdsd-wizard-anonymous-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/anonymous/step-components/step-gdsd-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/anonymous/steps-gdsd-dog-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/anonymous/steps-gdsd-personal-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/anonymous/steps-gdsd-selection.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/anonymous/steps-gdsd-training-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/common-step-components/step-gdsd-dog-medical.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/common-step-components/step-gdsd-other-trainings.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/common-step-components/step-gdsd-school-trainings.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/common-step-components/step-gdsd-training-history.component.ts

GDSD validation

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-category-armoured-car-guard.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-user-applications.component.ts

[FE] fix armour spelling

---

src/Spd.Manager.Screening/ApplicationContract.cs
src/Spd.Presentation.Screening/Controllers/ApplicationController.cs
src/Spd.Tests.Presentation.Screening/Integration/Controllers/ApplicationScenarios.cs

- [SPDBT-3596]Add Email Address to Generic Upload Files

[SPDBT-3596]Add Email Address to Generic Upload Files

---

src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Manager.Licence/GDSDAppValidation.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Manager.Licence/SharedContract.cs
src/Spd.Resource.Repository/Document/Contract.cs
src/Spd.Utilities.Dynamics/DynamicsContextLookupHelpers.cs

-[SPDBT-3610]OS-be-GDSD team certification-unautho-non-accredited school view model validation

[SPDBT-3610]OS-be-GDSD team certification-unautho-non-accredited school view model validation

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/validators/form-control.validators.ts

- SPDBT-3597 add apostrophe to email validation

SPDBT-3597 add apostrophe to email validation

---

src/Spd.Manager.Screening/ApplicationContract.cs
src/Spd.Manager.Screening/ApplicationManager.Delegate.cs
src/Spd.Presentation.Screening/Program.cs
src/Spd.Utilities.Shared/JsonConverts/TrimStringConverter.cs
src/Spd.Utilities.Shared/Spd.Utilities.Shared.csproj

- [SPDBT-3614] Screening - Add Delegate email validation not working

[SPDBT-3614] Screening - Add Delegate email validation not working

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/psso-portal/components/delegate-add-modal.component.ts

- SPDBT-3614 add email validation to delegate

SPDBT-3614 add email validation to delegate

---

src/Spd.Presentation.Licensing/Program.cs
src/Spd.Presentation.Licensing/Spd.Presentation.Licensing.csproj

- for licensing, as we need to do partial save, so, auto-validation should not apply.

remove auto validation for licensing

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/landing.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-access-code-authorized.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-active-swl-permit-licences.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-user-applications.component.ts

- SPDBT-3620, SPDBT-3621, SPDBT-3622 language updates
- Fix name formatting

SPDBT-3620, SPDBT-3621, SPDBT-3622 language updates

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/personal-licence-application-routes.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/personal-licence-application-routing.module.ts

- remove access to unauth permits

SPDBT-3425 - remove access to unauth permits

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/guide-dog-service-dog-landing.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/common-step-components/step-gdsd-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/common-step-components/step-gdsd-terms-of-use.component.ts

GDSD - block invalid flows

---

src/Spd.Manager.Licence/GDSDAppContract.cs

-fix SchoolTraining array validation

fix SchoolTraining array validation

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/user-profile-components/common-user-profile.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-criminal-history.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-first-time-user-selection.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-personal-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-physical-characteristics.component.ts

[SPDBT-3623, SPDBT-3624] Licensing language updates 

---

src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing/Controllers/GDSDLicensingController.cs
src/Spd.Resource.Repository/GDSDApp/Contract.cs
src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs
src/Spd.Resource.Repository/GDSDApp/Mappings.cs
src/Spd.Resource.Repository/SharedMappingFuncs.cs

- [SPDBT-3655]OS-be-GDSD auth Get GDSDApplication endpoint.

[SPDBT-3655]OS-be-GDSD auth Get GDSDApplication endpoint.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-licence-application-routing.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-main.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/steps-worker-licence-updates-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/personal-licence-main.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/steps-worker-licence-selection.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/personal-licence-application-routing.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/personal-licence-application.module.ts

- renamed a couple components.
- pass 'isSoleProprietorSimultaneousFlow' to category component so the message is only shown when appropriate.

[SPDBT-3658] SP error showing when not SP flow

---

src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs
src/Spd.Resource.Repository/GDSDApp/Mappings.cs
src/Spd.Utilities.Dynamics/ODataClientHandler.cs

[SPDBT-3613]make partial save working - part2

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-first-time-user-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-liability.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/steps-business-licence-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/steps-business-licence-swl-sp-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/step-controlling-member-aliases.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/step-controlling-member-consent-and-declaration.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/step-controlling-member-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/steps-controlling-member-personal-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/common-step-components/step-gdsd-photograph-of-yourself.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-photograph-of-yourself-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-application-type-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-step-components/step-permit-photograph-of-yourself-renew-and-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-step-components/step-permit-summary-review-update-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/user-profile-components/common-user-profile-licence-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-alias-list.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-swl-permit-terms-update-replace.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-first-time-user-selection.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-first-time-user-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-photograph-of-yourself-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-photograph-of-yourself-renew-and-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-address-autocomplete.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-alert-update-or-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-mental-health-conditions.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-photograph-of-yourself-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-photograph-of-yourself.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/step-section.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/shared.module.ts

- [SPDBT-3628, SPDBT-3629] Language updates
- Remove unused parameters

[SPDBT-3628, SPDBT-3629] Language updates

---

src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Manager.Licence/GDSDAppValidation.cs
src/Spd.Presentation.Licensing/Controllers/GDSDLicensingController.cs

- [SPDBT-3588] OS-be-GDSD team certification-auth-accredit school submit endpoint

[SPDBT-3588] OS-be-GDSD team certification-auth-accredit school submit endpoint

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/step-controlling-member-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/licence-category-locksmith.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/licence-category-private-investigator-sup.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/licence-category-private-investigator.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/licence-category-security-alarm-installer.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/licence-category-security-consultant.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/licence-category-security-guard.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-restraints.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-swl-citizenship.component.ts

- Clear the file-upload widget when document type changes (though a dropdown change or radio button change)

[SPDBT-3667] Clear file-upload widget

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-expired.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-consent-and-declaration.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-expired.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-rationale.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-reason.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-step-components/step-permit-summary-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-expired.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-bc-driver-licence.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-expired-licence.component.ts

- SPDBT-3631 Body Armour Update
- SPDBT-3632 Body Armour New
- SPDBT-3633 Body Armour Renewal
- SPDBT-3635 Armoured Vehicle Checklist
- SPDBT-3635 Body Armour New
- SPDBT-3636 Armoured Vehicle New

[FE] Language update - Permits

---

src/Spd.Resource.Repository/PortalUser/PortalUserRepository.cs

- [SPDBT-3653]for bizOrgPortalUser, as the figaro save BizGUID in uppercase, so, we need to compare bizGuid with case-insensitive in invitation

[SPDBT-3653]for bizOrgPortalUser, as the figaro save BizGUID in uppercase, so, we need to compare bizGuid with case-insensitive in invitation

---

src/Spd.Manager.Licence/ControllingMemberCrcAppContract.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Contract.cs
src/Spd.Resource.Repository/ControllingMemberCrcApplication/Mappings.cs

- [SPDBT-3662]Controlling Members - new question

[SPDBT-3662]Controlling Members - new question

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/code-types/model-desc.models.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-expired.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-expired.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/licence-category-locksmith.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/licence-category-private-investigator.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-expired.component.ts

- Licensing Portal Language Updates - SWL - Licence Category Selection

[SPDBT-3630] SWL - Licence Category Selection

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-category.component.ts

- Another tweak to showing/hiding SP categories error

[SPDBT-3658] SP Error

---

src/Spd.Manager.Licence/GDSDAppValidation.cs
src/Spd.Manager.Licence/LicenceAppDocumentManager.cs

gdsd integration fix

---

src/Spd.Manager.Licence/SecurityWorkerAppContract.cs
src/Spd.Manager.Licence/SecurityWorkerAppManager.cs
src/Spd.Presentation.Licensing/Controllers/LicenceAppController.cs

-[SPDBT-3671]OS-be-GDSD list all GDSD application for the login applicant.

[SPDBT-3671]OS-be-GDSD list all GDSD application for the login applicant.

---

src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs

partial save, process null

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-list-current.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/licence-active-swl-permit-licences.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-photograph-of-yourself-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-photograph-of-yourself.component.ts

- allow Replacements anytime
- photo bullets - remove periods

[FE] Allow Replacements anytime

---

src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs
src/Spd.Resource.Repository/GDSDApp/Mappings.cs

- update contact when partial save

update contact when partial save

---

src/Spd.Manager.Licence/Constants.cs
src/Spd.Manager.Licence/PermitAppManager.cs
src/Spd.Manager.Licence/SecurityWorkerAppManager.cs

- [SPDBT-3683]Allow Replacements at any time

[SPDBT-3683]Allow Replacements at any time

---

src/Spd.Manager.Licence/BizProfileContract.cs
src/Spd.Manager.Licence/BizProfileManager.cs
src/Spd.Manager.Licence/Constants.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/LoginControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/LoginController.cs
src/Spd.Presentation.Licensing/appsettings.json

- [SPDBT-3673]Make a feature switch for biz bceid login in licensing. Do not allow user to select any one org from the org list.

[SPDBT-3673]Make a feature switch for biz bceid login in licensing. Do not allow user to select any one org from the org list.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/landing.component.ts

- SPDBT-3699 - language updates

SPDBT-3699 - language updates

---

src/Spd.Manager.Licence/Constants.cs
src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Manager.Licence/GDSDAppValidation.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Manager.Licence/PermitAppManager.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/GDSDLicensingControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/GDSDLicensingController.cs
src/Spd.Resource.Repository/GDSDApp/Contract.cs
src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs
src/Spd.Resource.Repository/GDSDApp/Mappings.cs
src/Spd.Resource.Repository/Licence/Contract.cs
src/Spd.Resource.Repository/SharedRepositoryFuncs.cs

-[SPDBT-3693]OS-be-GDSD team certification renew endpoint.

[SPDBT-3693]OS-be-GDSD team certification renew endpoint.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/app-routes.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-license-application-routes.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/controlling-member-crc-routes.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/guide-dog-service-dog-routes.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/metal-dealers-and-recyclers-routes.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/personal-licence-application-routes.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/security-licence-status-verification/security-licence-status-verification-routes.ts

Module path bug fix

---

src/Spd.Manager.Licence/GDSDAppContract.cs

fix gdsd get

---

src/Spd.Manager.Licence.UnitTest/GDSDAppValidationTest.cs
src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Manager.Licence/GDSDAppValidation.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Resource.Repository/GDSDApp/Contract.cs
src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs
src/Spd.Resource.Repository/GDSDApp/Mappings.cs

- view model refactor, leading to manager refactor and repository refactor

refactor gdsd: new and renew

---

src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs

add null protection

---

src/Spd.Presentation.Licensing/Controllers/GDSDLicensingController.cs

- [SPDBT-3694]unauth and auth replace and renew

[SPDBT-3694]unauth and auth replace and renew

---

src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Presentation.Licensing/Controllers/GDSDLicensingController.cs

add replacement for gdsd

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

-    fix lic lookup endpoint for gdsd

fix lic lookup endpoint for gdsd

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

-add cookie for applicant for gdsd licence lookup

add cookie for applicant for gdsd licence lookup

---

src/Spd.Manager.Licence/GDSDAppValidation.cs
src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

fix validation and photo

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

- fix - licence lookup : null response

fix - licence lookup : null response

---

src/Spd.Manager.Licence/DogTrainerAppContract.cs
src/Spd.Manager.Licence/DogTrainerAppManager.cs
src/Spd.Manager.Licence/DogTrainerAppValidation.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing/Controllers/DogTrainerLicensingController.cs
src/Spd.Resource.Repository/Configurer.cs
src/Spd.Resource.Repository/DogTrainerApp/Contract.cs
src/Spd.Resource.Repository/DogTrainerApp/DogTrainerAppRepository.cs
src/Spd.Resource.Repository/DogTrainerApp/Mappings.cs

- [SPDBT-3733] OS-be-dog-trainer create endpoint for new dog trainer certification.

[SPDBT-3733] OS-be-dog-trainer create endpoint for new dog trainer certification.

---

src/Spd.Manager.Common/Admin/AdminManager.cs
src/Spd.Manager.Common/Admin/Contract.cs
src/Spd.Manager.Common/Admin/Mappings.cs
src/Spd.Manager.Licence/DogTrainerAppContract.cs
src/Spd.Manager.Licence/DogTrainerAppValidation.cs
src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppValidation.cs
src/Spd.Presentation.Licensing/Controllers/DogSchoolController.cs
src/Spd.Resource.Repository/DogTrainerApp/Contract.cs
src/Spd.Resource.Repository/DogTrainerApp/DogTrainerAppRepository.cs
src/Spd.Resource.Repository/GDSDApp/Contract.cs
src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs

- [SPDBT-3676]OS-be-GDSD team certification: return the list of the accredited school.
- refactor GDSD and dogTrainer to add school id

[SPDBT-3676]OS-be-GDSD team certification: return the list of the accredited school.

---

src/Spd.Resource.Repository/GDSDApp/Mappings.cs

- fix -get gdsd app , add accredit school id in response

fix -get gdsd app , add accredit school id in response

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs
src/Spd.Resource.Repository/PersonLicApplication/PersonLicApplicationRepository.cs

[SPDBT-3706]Mental Health Condition language updates

[SPDBT-3706]Mental Health Condition language updates

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/steps-business-licence-updates.component.ts

- [SPDBT-3741] Business License Update Flow to Include Employees

[SPDBT-3741] Business License Update Flow to Include Employees

---

src/Spd.Presentation.Licensing/Controllers/ApplicantProfileController.cs

- be - anonymous - return if any applications are in progress - swl and permits

[SPDBT-3798]be - anonymous - return if any applications are in progress - swl and permits

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-controlling-members.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-controlling-members.component.ts

- "Corporate Registry documents" mandatory for renewals

SPDBT-3780 "Corporate Registry documents" mandatory for renewals

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-term.component.ts

- "Security Guard - Under Supervision" 90 day term

SPDBT-3770 "Security Guard - Under Supervision" term

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/payment-filter.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/payments.component.ts

- toggle paid / not paid (change to radio buttons)
- fix bug with from/to date. Will show at most the last year of data.
- will show as Paid if paidOn has a value (regardless of status)

[SPDBT-3799] UI screening payment 

---

src/Spd.Presentation.Licensing/ClientApp/package-lock.json
src/Spd.Presentation.Licensing/ClientApp/package.json
src/Spd.Presentation.Screening/ClientApp/package-lock.json
src/Spd.Presentation.Screening/ClientApp/package.json

Angular Upgrades

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/dog-trainer-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/gdsd-team-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/retired-dog-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/landing.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/dog-trainer/step-dt-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-landing.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-team/step-team-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/step-rd-dog-living-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/step-rd-dog-retired-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/step-rd-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/steps-rd-dog-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/steps-rd-personal-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/step-title.component.ts

GDSD - various flows

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/dog-trainer-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/gdsd-team-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/retired-dog-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/dog-trainer/dog-trainer-wizard-new-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/dog-trainer/dog-trainer-wizard-replacement.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/dog-trainer/step-dt-licence-access-code.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-team/gdsd-team-wizard-new-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-team/gdsd-team-wizard-replacement.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-team/step-team-licence-access-code.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/retired-dog-wizard-new-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/retired-dog-wizard-replacement.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/step-rd-licence-access-code.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/form-gdsd-licence-access-code.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/form-gdsd-personal-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-replacement.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-replacement.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts

GDSD flow updates

---

src/Spd.Presentation.Screening/ClientApp/src/app/app.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/crrp.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/psso-portal/psso.component.ts

- SPDBT-3908 - load ministries after login to crrp or psso

[SPDBT-3908] - screening - load ministries 

---

src/Spd.Resource.Repository/ControllingMemberCrcApplication/ControllingMemberCrcRepository.cs

- [SPDBT-3881] error submitted business licence with controlling members

[SPDBT-3881] error submitted business licence with controlling members

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/gdsd-team-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/retired-dog-application.service.ts

gdsd - turn on partial save

---

src/Spd.Manager.Printing/Documents/TransformationStrategies/Mappings.cs

- forget issuedDate for biz licence in printing

forget issuedDate for biz licence in printing

---

src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Printing/Documents/TransformationStrategies/Mappings.cs
src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs

- [SPDBT-3895]GDSD Team - Partial save

[SPDBT-3895] GDSD Team - Partial save

---

src/Spd.Resource.Repository/GDSDApp/Mappings.cs

- [SPDBT-3909]Default 'Dog Type' to 'Service Dog' for unaccredited GDSD applications

[SPDBT-3909] Default 'Dog Type' to 'Service Dog' for unaccredited GDSD applications

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts

[SPDBT-3926] Trimmed and case insensitive name comparison

---

src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs

fix-unauth gdsd new

---

src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Resource.Repository/GDSDApp/Contract.cs
src/Spd.Resource.Repository/GDSDApp/Mappings.cs

- [SPDBT-3869] GDSD Team - new doctor providing medical form

[SPDBT-3869]GDSD Team - new doctor providing medical form

---

src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs

fix partial save again

---

src/Spd.Resource.Repository/Application/ApplicationRepository.Application.cs
src/Spd.Resource.Repository/Application/Contract.Application.cs
src/Spd.Resource.Repository/Application/Mappings.cs
tools/splunk/ClearanceNotificationErrorSplunkSearchQuery.txt
tools/splunk/MissingPaymentSplunkSearchQuery.txt

- [SPDBT-3824]Clearance Access Error Notification in SPLUNK

[SPDBT-3824]Clearance Access Error Notification in SPLUNK

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-team/gdsd-team-wizard-new-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/retired-dog-wizard-new-renewal.component.ts

GDSD fix display of 'save and exit' on renewal

---

src/Spd.Manager.Licence.UnitTest/BizLicenceAppManagerTest.cs
src/Spd.Manager.Licence.UnitTest/BizPortalUserManagerTest.cs
src/Spd.Manager.Licence.UnitTest/BizProfileManagerTest.cs
src/Spd.Manager.Printing/Documents/TransformationStrategies/BizLicencePrintingTransformStrategy.cs
src/Spd.Resource.Repository/Biz/BizRepository.cs
src/Spd.Resource.Repository/Biz/Contract.cs
src/Spd.Resource.Repository/Biz/Mappings.cs
src/Spd.Utilities.Dynamics/OptionSets.cs

- [SPDBT-3952]Licensing - JSON to include Main Office branch

[SPDBT-3952]Licensing - JSON to include Main Office branch

---

src/Spd.Resource.Repository/Biz/Mappings.cs

fix biz profile mapping

---

src/Spd.Resource.Repository/Biz/Mappings.cs

fix biz map for sonar

---

src/Spd.Manager.Licence/PermitAppManager.cs
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-update-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-licence-category-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/shared.module.ts

- common component for licence category summary
- summary ui tweaks
- licence lookup, handle Preview licence

[Licensing] minor updates

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/code-types/model-desc.models.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/auth-process.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-licence-application-routing.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-license-application-routes.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-main.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/modal-portal-administrator-edit.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/portal-administrator-invitation.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/portal-administrators.component.ts

- Change 'business manager' language to 'portal administrator'

[SPDBT-3962] update business manager text

---

src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Resource.Repository/GDSDApp/Contract.cs
src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs

- [SPDBT-3969] GDSD - Non-BCSC application created a case with no identity confirmed

[SPDBT-3969] GDSD - Non-BCSC application created a case with no identity confirmed

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/dog-trainer-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/gdsd-team-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/dog-trainer/dog-trainer-wizard-new-renewal.component.ts

- fix totalTrainingHours bug
- fix dog trainer submission
- [SPDBT-3974] licence lookup fix

[gdsd] minor bugs + [SPDBT-3974]

---

src/Spd.Manager.Licence/DogTrainerAppContract.cs
src/Spd.Manager.Licence/DogTrainerAppManager.cs
src/Spd.Manager.Licence/DogTrainerAppValidation.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing/Controllers/DogTrainerLicensingController.cs
src/Spd.Resource.Repository/DogTrainerApp/Contract.cs
src/Spd.Resource.Repository/DogTrainerApp/DogTrainerAppRepository.cs
src/Spd.Resource.Repository/DogTrainerApp/Mappings.cs

- [SPDBT-3977] Dog Trainer - implement anonymous get endpoint

[SPDBT-3977] Dog Trainer - implement anonymous get endpoint

---

src/Spd.Manager.Licence/DogTrainerAppContract.cs
src/Spd.Manager.Licence/DogTrainerAppManager.cs
src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing/Controllers/DogTrainerLicensingController.cs
src/Spd.Resource.Repository/DogBase/Contract.cs
src/Spd.Resource.Repository/DogBase/DogAppBaseRepository.cs
src/Spd.Resource.Repository/DogTrainerApp/Contract.cs
src/Spd.Resource.Repository/DogTrainerApp/DogTrainerAppRepository.cs
src/Spd.Resource.Repository/GDSDApp/Contract.cs
src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs

more
change
dog trainer change
- [SPDBT-3899] Dog Trainer - implement anonymous change endpoint

[SPDBT-3899] Dog Trainer - implement anonymous change endpoint

---

src/Spd.Manager.Licence/GDSDAppContract.cs
src/Spd.Manager.Licence/GDSDAppManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing.UnitTest/Controller/GDSDLicensingControllerTest.cs
src/Spd.Presentation.Licensing/Controllers/GDSDTeamLicensingController.cs
src/Spd.Resource.Repository/DogTrainerApp/Mappings.cs

- fix issues on integration dog trainer

fix issues on integration dog trainer

---

src/Spd.Manager.Licence/BizMemberContract.cs
src/Spd.Manager.Licence/BizMemberManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing/Controllers/BizMembersController.cs
src/Spd.Resource.Repository/BizContact/Contract.cs
src/Spd.Utilities.Dynamics/OptionSets.cs

- [SPDBT-3981] BE - Security Business License Business Managers

[SPDBT-3981] BE - Security Business License Business Managers

---

src/Spd.Resource.Repository/BizContact/BizContactRepository.cs

- fix bug for update biz manager

fix bug for update biz manager

---

src/Spd.Manager.Printing/Documents/TransformationStrategies/PersonalLicencePreviewTransformStrategy.cs

- [SPDBT-3747] GDSD Retired dog, licence preview for bcmp printing

[SPDBT-3747] GDSD Retired dog, licence preview for bcmp printing

---

src/Spd.Manager.Licence/LicenceManager.cs

- [SPDBT-3900][SPDBT-3903] GDSD Retired Dog - implement change endpoint for unauth and auth

[SPDBT-3900][SPDBT-3903] GDSD Retired Dog - implement change endpoint for unauth and auth

---

src/Spd.Resource.Repository/DogTrainerApp/DogTrainerAppRepository.cs
src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs
src/Spd.Resource.Repository/SharedRepositoryFuncs.cs

- [SPDBT-3996] GDSD Training Event Ownership

[SPDBT-3996] GDSD Training Event Ownership

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts

- Fix population of dogs / restraints in model from licence

[FE] dogs / restraints from licence

---

src/Spd.Manager.Licence/BizMemberContract.cs
src/Spd.Presentation.Dynamics/Controllers/OrgController.cs
src/Spd.Presentation.Dynamics/Spd.Presentation.Dynamics.csproj
src/Spd.Presentation.Dynamics/appsettings.json
src/Spd.Resource.Repository/ControllingMemberInvite/Contract.cs
src/Spd.Resource.Repository/ControllingMemberInvite/ControllingMemberInviteRepository.cs

- [SPDBT-4008] Dynamics Helper: Provide an endpoint to create an invitation for business contact in spd_portalinvitation entity.

[SPDBT-4008] Dynamics Helper: Provide an endpoint to create an invitation for business contact in spd_portalinvitation entity.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/business-licence-application.module.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-stakeholders.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-new-swl-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-renewal-swl-sole-proprietor.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-wizard-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-employees-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-employees.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/steps-business-licence-controlling-members.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/steps-business-licence-sp-employees.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/steps-business-licence-swl-sp-information.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/steps-business-licence-updates.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-category.component.ts

- SPDBT-3981 - fix language
- cm/bm validation
- SPDBT-3998 remove sp category validation, add employees step to sp flows.

[SPDBT-3998] remove sp category validation

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/controlling-member-wizard-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/controlling-member-wizard-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-anonymous-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-anonymous-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-anonymous-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-summary-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/steps-permit-details-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/steps-permit-details-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-authenticated-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/permit-wizard-step-components/step-permit-summary-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/steps-worker-licence-selection.component.ts

- simplify component/step matching
- bug: permit was not validating criminal history in the wizard
- bug: fix some summary 'edit' button labels and navigation
- bug: make display of 'next: review' button display consistent in all wizards
- bug: do not set dog/restraints in model without a SecurityGuard category

[FE] swl/permit bug fixes

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrpa-portal/crrpa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/pssoa-portal/pssoa.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-eligibility.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-organization-info.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-personal-info.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/sa-step-terms-and-cond.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-consent-to-crc.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-contact-information.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-declaration.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-personal-information.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-security-information.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/screening-application-steps/step-components/sa-summary.component.ts

- move check for orgData to parent component

[SPDBT-3955] Screening- fix issue when logging in ecrc flow

---

src/Spd.Presentation.Licensing/Controllers/ApplicantProfileController.cs

- add an endpoint for anonymous gdsd apps

add an endpoint for anonymous gdsd apps

---

src/Spd.Resource.Repository/RetiredDogApp/Mappings.cs

- add retired dog default mapping

add retired dog default mapping

---

src/Spd.Manager.ScheduleJob/Contract.cs
src/Spd.Manager.ScheduleJob/ScheduleJobManager.cs
src/Spd.Presentation.Dynamics/Controllers/ScheduleJobController.cs
src/Spd.Presentation.Dynamics/appsettings.json
src/Spd.Resource.Repository.JobSchedule/Org/Contract.cs
src/Spd.Resource.Repository.JobSchedule/Org/OrgRepository.cs
src/Spd.Resource.Repository.JobSchedule/ScheduleJobSession/Mappings.cs
src/Spd.Resource.Repository.JobSchedule/ScheduleJobSession/ScheduleJobSessionRepository.cs
src/Spd.Utilities.Dynamics/Configurer.cs

- multi-request is being cancelled. Becuase of cancellation Token. Add infinite concellationToken
- read concurrent requests from config
- add paging in case the orgs is more than 5000.

[SPDBT-3836] fix request was cancelled issue

---

src/Spd.Resource.Repository/DogBase/DogAppBaseRepository.cs
src/Spd.Resource.Repository/LicApp/LicAppRepository.cs

- [SPDBT-4034] [Licensing] Updating anonymous SWL not using latest application

[SPDBT-4034] [Licensing] Updating anonymous SWL not using latest application

---

src/Spd.Resource.Repository/Biz/BizRepository.cs

- [SPDBT-4035]Business Licence SP not saving PI data

[SPDBT-4035]Business Licence SP not saving PI data

---

src/Spd.Manager.Licence/BizLicAppValidation.cs
src/Spd.Manager.Licence/SecurityWorkerAppValidation.cs
src/Spd.Resource.Repository/Biz/BizRepository.cs

- [Licensing] Show better msg for exceeding max categories

[Licensing] Show better msg for exceeding max categories

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts

- [SPDBT-4040] fix saving applicant is manager flag

[SPDBT-4040] fix saving applicant is manager flag

---

src/Spd.Manager.Licence/LicenceManager.cs

-[SPDBT-4058] For unauth, swl licence search, should remove preview status.

[SPDBT-4058] For unauth, licence search, should remove preview status.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts

[SPDBT-4063] SP PI validation

---

src/Spd.Presentation.Screening/ClientApp/src/app/modules/pssoa-portal/pssoa.component.ts

- [SPDBT-4065] pssoa post login navigate to 4th step.

[SPDBT-4065] pssoa post login

---

src/Spd.Resource.Repository.JobSchedule/GeneralizeScheduleJob/GeneralizeScheduleJobRepository.cs

-Schedule Job Dynamics End Point response mapping

[SPDBT-4061] Schedule Job Dynamics End Point response mapping

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts

- [SPDBT-4075] fix display of criminal history step in the update flow
- Make worker and permit service consistent in how they populate the data.

[SPDBT-4075] fix display of criminal history step in the update flow

---

src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/BizLicAppValidation.cs
src/Spd.Manager.Licence/PermitAppManager.cs
src/Spd.Manager.Licence/PermitAppValidation.cs
src/Spd.Manager.Licence/SecurityWorkerAppManager.cs
src/Spd.Manager.Licence/SecurityWorkerAppValidation.cs

- [SPDBT-4076] Remove file checkings

[SPDBT-4076] Remove file checkings

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-summary-review-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/step-worker-licence-summary-review-update-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-licence-category-panel-simple.component.ts

- Allow update flows to change category data

[SPDBT-4072] Allow update flows to change category data

---

src/Spd.Manager.ScheduleJob/ScheduleJobManager.cs

-[SPDBT-4086]schedule job: fix the "property not found" issue.

[SPDBT-4086]schedule job: fix the "property not found" issue.

---

src/Spd.Manager.ScheduleJob/ScheduleJobManager.cs
src/Spd.Resource.Repository.JobSchedule/Org/Contract.cs
src/Spd.Resource.Repository.JobSchedule/Org/OrgRepository.cs

-[SPDBT-4087]Schedule job: when run on staging env, we got "out of memory" exception. Need to investigate.

[SPDBT-4087] Schedule job: when run on staging env, we got "out of memory" exception. Need to investigate.

---

src/Spd.Resource.Repository.JobSchedule/Org/OrgRepository.cs
src/Spd.Resource.Repository/BizContact/Mappings.cs
src/Spd.Resource.Repository/BizLicApplication/Contract.cs
src/Spd.Utilities.Dynamics/DynamicsContextLookupHelpers.cs

-[SPDBT-4089] STAGING - Unable to update existing Business Licence

[SPDBT-4089] STAGING - Unable to update existing Business Licence

---

src/Spd.Manager.ScheduleJob/ScheduleJobManager.cs
src/Spd.Presentation.Dynamics/Controllers/ScheduleJobController.cs
src/Spd.Presentation.Dynamics/Program.cs
src/Spd.Presentation.Dynamics/Services/IScheduleJobQueue.cs
src/Spd.Presentation.Dynamics/Services/ScheduleJobProcessor.cs
src/Spd.Presentation.Dynamics/Services/ScheduleJobQueue.cs
src/Spd.Resource.Repository.JobSchedule/Org/Contract.cs
src/Spd.Resource.Repository.JobSchedule/Org/OrgRepository.cs

- [SPDBT-4087] Memory leak fix

[SPDBT-4087] Memory leak fix

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts

- SPDBT-4088 - default hasBcDriversLicence flag to false on submission
- SPDBT-4068 - Fix setting of applicationIsBizManager flag for submission

Licensing - SPDBT-4088, SPDBT-4068

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-licence-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts

-save bizInsurance documents in update flow
-remove unused parameter

SPDBT-4105 - save bizInsurance documents

---

src/Spd.Manager.Licence/BizLicAppManager.cs
src/Spd.Manager.Licence/LicenceAppManagerBase.cs
src/Spd.Manager.Licence/PermitAppManager.cs
src/Spd.Manager.Licence/SecurityWorkerAppManager.cs

- [SPDBT-4077] If new documents uploaded in update flow, we need to show them in the summary.

[SPDBT-4077] If new documents uploaded in update flow, we need to show them in the summary.

---

src/Spd.Manager.Printing/Documents/TransformationStrategies/Mappings.cs

- [SPDBT-4107] Print Preview: Get the applicant Name printed on card from licence nameOnCard field.

[SPDBT-4107] Print Preview: Get the applicant Name printed on card from licence nameOnCard field.

---

src/Spd.Manager.Licence/BizPortalUserManager.cs
src/Spd.Manager.Licence/BizProfileManager.cs

- [SPDBT-4095] biz have portal administrator that does not have identity

[SPDBT-4095] biz have portal administrator that does not have identity

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/manual-submission-common.component.ts

…om licence nameOnCard field. (#2576)
- SPDBT-4106 - fix setting of ServiceType

[SPDBT-4106] - fix setting of ServiceType

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/step-controlling-member-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/steps-worker-licence-identification-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-step-components/steps-worker-licence-identification-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-citizenship.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-swl-citizenship.component.ts

- SPDBT-4108 - handle null isCanadianCitizen

SPDBT-4108 - handle null isCanadianCitizen

---

src/Spd.Resource.Repository/Biz/Mappings.cs

- [SPDBT-4112] staging: some biz cannot get correct service type in getBizProfile.

[SPDBT-4112] staging: some biz cannot get correct service type in getBizProfile.

---

src/Spd.Manager.Licence/ControllingMemberCrcAppValidation.cs
src/Spd.Manager.Licence/LicenceAppValidation.cs

- [SPDBT-4110] [STAGING] Error with 'isCanadianCitizen'

[SPDBT-4110] [STAGING] Error with 'isCanadianCitizen'

---

src/Spd.Manager.Licence/BizLicAppBaseValidation.cs

- [SPDBT-4118] for biz licence replacement, remove IsApplicantBizManager validation.

[SPDBT-4118] for biz licence replacement, remove IsApplicantBizManager validation.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/landing.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/common-business-information.component.ts

- move url to a constant
- update error message

[Licensing] minor stuff

---

src/Spd.Manager.Licence/LicenceManager.cs

- [SPDBT-4125]Select some "Preview" status licence get error

[SPDBT-4125]Select some "Preview" status licence get error

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-expired.component.ts

- [SPDBT-4130] force save if licenceAppId is null

[SPDBT-4130] force save if licenceAppId is null

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/interceptors/error.interceptor.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/dialog-oops.component.ts

- [SPDBT-4135] hide error details in Prod

[SPDBT-4135] hide error details in Prod

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/dog-trainer-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/gdsd-team-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/retired-dog-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/authenticated/gdsd-licence-main.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/dog-trainer/step-dt-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/dog-trainer/steps-dt-details.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-base-authenticated.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-team/step-team-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-team/steps-team-selection.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/step-rd-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/retired-dog/steps-rd-details.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/step-gdsd-terms-of-use.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/guide-dog-service-dog.module.ts

- fix back button issues
- fix terms of use - make common component

[GDSD] bug fixes

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts

- [SPDBT-4139] enforce max of 6 sbl categories

[SPDBT-4139] enforce max of 6 sbl categories

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-category.component.ts

- [SPDBT-4049] display warning message when 6 categories reached - swl and sbl

[SPDBT-4049] display warning message when 6 categories reached

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-application-type-anonymous.component.ts

[Licensing] spelling mistake

---

src/Spd.Presentation.GuideDogServiceDog/Program.cs
src/Spd.Presentation.GuideDogServiceDog/Spd.Presentation.GuideDogServiceDog.csproj
src/Spd.sln

- [SPDBT-4129]New GDSD proj - part1

[SPDBT-4129]New GDSD proj - part1

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/dog-trainer/step-dt-dog-trainer-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/dog-trainer/step-dt-training-school-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-team/step-team-other-trainings.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/gdsd-team/step-team-school-trainings.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/guide-dog-service-dog/components/shared/form-gdsd-personal-info-anonymous.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/modal-mdra-branch.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-manager.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-owner.component.ts

[GDSD] remove optional label

---

src/Spd.Presentation.Licensing/ClientApp/src/index.html

[SPDBT-4164] update title

---

src/Spd.Manager.Printing/Documents/TransformationStrategies/Mappings.cs
src/Spd.Resource.Repository/SharedMappingFuncs.cs

- [SPDBT-4162]When do licence preview, we need to ignore the case of the height and weight. Mapping height and weight.

[SPDBT-4162]When do licence preview, we need to ignore the case of the height and weight. Mapping height and weight.

---

src/Spd.Presentation.Licensing/ClientApp/src/app/app-routing.module.ts

[Licensing] remove access to mdra and gdsd

---

src/Spd.Resource.Repository/GDSDApp/Mappings.cs

- [SPDBT-4144] Setting Spayed or Neutered Automatically for Accredited Schools

[SPDBT-4144] Setting Spayed or Neutered Automatically for Accredited Schools

---

src/Spd.Manager.Printing/Documents/TransformationStrategies/PersonalLicencePreviewTransformStrategy.cs
src/Spd.Resource.Repository/Licence/Contract.cs
src/Spd.Resource.Repository/Licence/Mappings.cs
src/Spd.Utilities.Printing/Printer.cs

- [SPDBT-4099] GDSD - Update Dog Trainer JSON logic

[SPDBT-4099] GDSD - Update Dog Trainer JSON logic

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-anonymous-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts

- SPDBT-4188 
- unauthenticated - always show citizenship question in renewal
- authenticated - show citizenship question in renewal when not a canadian citizen.

[SPDBT-4188] Licensing - Citizenship question for Renewal

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts

- SPDBT-4200 - Access code response for invalid combination. Show the proper error message

[SPDBT-4200] Licensing - Access code response for invalid combination

---

src/Spd.Presentation.GuideDogServiceDog/appsettings.json
src/Spd.Resource.Repository/DogTrainerApp/Mappings.cs
src/Spd.Resource.Repository/GDSDApp/Mappings.cs
src/Spd.Resource.Repository/RetiredDogApp/Mappings.cs

- [SPDBT-4174] Dog Trainer applicant name

[SPDBT-4174] Dog Trainer applicant name

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts

[GDSD] fix display of access code error message

---

src/Spd.Presentation.Licensing/Program.cs

- [SPDBT-4167] Fix health check for licensing

[SPDBT-4167] Fix health check for licensing

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/alert.component.ts

[GDSD] alert visual updates

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/authenticated/worker-licence-wizard-authenticated-renewal.component.ts

- [SPDBT-4188] swl auth renewal with missing isCanadianCitizen flag. Revert the change which removed this code.

[SPDBT-4188] swl auth renewal with missing isCanadianCitizen flag

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/authenticated/gdsd-licence-main-applications-list.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/dog-trainer-wizard-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-application-type.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-licence-confirmation.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/gdsd-team-wizard-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-application-type.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-licence-confirmation.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/retired-dog-wizard-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-application-type.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-licence-confirmation.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-application-type.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-licence-confirmation.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts

- [SPDBT-3993] - gdsd language updates

[SPDBT-3993] - gdsd language updates

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-checklist-renewal.component.ts

- Dog Trainer Renewal Checklist - add missing text

[GDSD] Dog Trainer Renewal Checklist

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/steps-permit-details-new.component.ts

- Body Armour Permit New Checklist updates

[SPDBT-4244] Body Armour Permit New Checklist updates

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-dog-trainer-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-school-trainings.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-dog-retired-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-accredited-school.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-dog-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-goverment-photo-id.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-personal-info-anonymous.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/file-upload.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/spd-header.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/step-title.component.ts

- fix autocomplete bug- issue selecting with mouse
- fix date validation

[GDSD] fix accessibility bugs

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/captcha-v2.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/file-upload.component.ts

- add invisible recaptcha
- fix date bug
-

[GDSD] SPDBT-99 frontend updates

---

src/Spd.Manager.Licence/LicenceContract.cs
src/Spd.Manager.Licence/Mappings.cs

- [SPDBT-4257]Security Worker License Lookup include AST - backend

[SPDBT-4257]Security Worker License Lookup include AST - backend

---

src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/licence-basic-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/api/models/licence-response.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/security-licence-status-verification/components/security-licence-status-verification-swl.component.ts

SPDBT-4257 - Add 'security guard - AST'

---

src/Spd.Manager.Licence/MDRARegistrationManager.cs
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/metal-dealers-application.helper.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/metal-dealers-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/steps-controlling-member-background.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/form-mdra-branches.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/mdra-wizard-new-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/mdra-wizard-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-access-code.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-application-type.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-branches.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-address-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-address.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-manager.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-owner-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-owner.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-checklist-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-summary.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/steps-mdra-branches.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/steps-mdra-business-info-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/steps-mdra-business-info.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/steps-mdra-details.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/metal-dealers-and-recyclers.module.ts

- SPDBT-3855 - agree to update
- SPDBT-4221 - update integration
- SPDBT-4220 - renewal integration

[MDRA] renew / update

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-consent.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-consent.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-consent.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-consent-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/gdsd-common-application.helper.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/step-section.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/step-title.component.ts

- remove first checkbox from consent
- add main and header tags

[GDSD] accessibility [SPDBT-99]

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-manager.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-consent.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-terms-of-use.component.ts

- [SPDBT-4048] fix terms
- fix heading

[SPDBT-4048] fix terms

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/authenticated/gdsd-licence-main.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/dog-trainer-wizard-new-renewal.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/dog-trainer-wizard-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-dog-trainer-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-summary.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-training-school-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-base-anonymous.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-base-authenticated.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-landing.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/gdsd-team-wizard-new-renewal.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/gdsd-team-wizard-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-other-trainings.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-school-trainings.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-summary.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/steps-team-dog-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/retired-dog-wizard-new-renewal.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/retired-dog-wizard-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-summary.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-personal-info-anonymous.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-personal-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/gdsd-application-received.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/components/base-wizard.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/container.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/step-section.component.ts

[SPDBT-99] Accessibility updates

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-terms-of-use.component.ts

[SPDBT-4048] - MDRA fix text

---

src/Spd.Presentation.GuideDogServiceDog/Controllers/LicenceController.cs
src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

- when no licence found, should return no content for licence lookup endpoint

when no licence found, should return no content for licence lookup endpoint

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/metal-dealers-landing.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-access-code.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-application-type.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-licence-expired.component.ts

- [SPDBT-3855] update MDRA phone

[SPDBT-3855] update MDRA phone

---

src/Spd.Presentation.Licensing/Controllers/PaymentController.cs
src/Spd.Presentation.Screening/Controllers/PaymentController.cs

- [SPDBT-4274] "Payment cancel" code change needs to accommodate paybc changes.

[SPDBT-4274] "Payment cancel" code change needs to accommodate paybc changes.

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

- licensing be : add recaptcha to verification tool

licensing be: add recaptcha to verification tool

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

- [SPDBT-4255] Bulk swl lookup - find matching swl number from user input

[SPDBT-4255] Bulk swl lookup - find matching swl number from user input

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/security-licence-status-verification/components/security-licence-status-verification-main.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/security-licence-status-verification/components/security-licence-status-verification-sbl.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/security-licence-status-verification/components/security-licence-status-verification-swl.component.ts

[SPDBT-4308] Language updates

---

src/Spd.Presentation.Licensing/Configurations/PaymentsConfiguration.cs
src/Spd.Presentation.Licensing/Controllers/PaymentController.cs

[SPDBT-4306] business licence cancel payment

---

src/Spd.Resource.Repository/Application/ApplicationRepository.Application.cs

- [SPDBT-3973] Screening [PROD]: Error When Searching Names with Apostrophes in Org Portal

[SPDBT-3973] Screening [PROD]: Error When Searching Names with Apostrophes in Org Portal

---

src/Spd.Presentation.Screening/ClientApp/src/app/core/constants/constants.ts

[SPDBT-4324] fix screening typo

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-consent.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-dog-trainer-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-accredited-graduation.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-consent.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-school-trainings.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-consent.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-dog-retired-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-gdsd-certificate.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-accredited-school.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-consent-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-personal-info-anonymous.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/retired-dog-application.helper.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/retired-dog-application.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts

- Replace 'Current Certification Number' free-form field to a licence lookup
- Removed unused declarations
- Change recaptcha error message (approved by Sarah)

[SPDBT-4342] Add licence lookup to Retired Dog New

---

src/Spd.Presentation.Licensing/ClientApp/src/app/app-routing.module.ts

MDRA - hide

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

- [SPDBT-4396] Bulk License Lookup License Parameter Update

[SPDBT-4396] Bulk License Lookup License Parameter Update

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/worker-licence-wizard-step-components/step-worker-licence-access-code.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-user-profile.component.ts

- prevent back button resubmission

[SPDBT-4098] prevent back button resubmission

---

src/Spd.Manager.Licence/LicenceManager.cs
src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

- [SPDBT-4392] Bulk License Lookup License Parameter Update , make it more friendly

[SPDBT-4392] Bulk License Lookup License Parameter Update , make it more friendly

---

.gitignore
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Manager.Licence/SharedContract.cs
src/Spd.Resource.Repository/Document/Contract.cs
src/Spd.Utilities.Dynamics/DynamicsContextLookupHelpers.cs

- [SPDBT-4429]be: add DogTrainer Accredited School Verification document type

[SPDBT-4429]be: add DogTrainer Accredited School Verification document type

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/business-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/metal-dealers-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/form-mdra-licence-access-code.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-owner-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/metal-dealers-and-recyclers/components/step-mdra-business-owner.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts

- Fix MDRA reset 
- Fix label
- Licence lookup - remove check for 'apps in progress'

[SPDBT-4421] MDRA fixes

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/api/models/licence-document-type-code.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/app.module.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-checklist-new.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-checklist-renewal.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-summary.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-training-school-ceo.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-training-school-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-training-school-verification.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/steps-dt-training-school-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-summary.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-summary.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/dog-trainer-application.helper.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/dog-trainer-application.service.ts

[SPDBT-4429] dog trainer school verification

---

src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-licence-main.component.ts

- [SPDBT-4437] turn off SBL link

[SPDBT-4437] turn off SBL link

---

src/Spd.Manager.Licence/SecurityWorkerAppManager.cs

[SPDBT-4179] Null Peace Officer Status Triggering Update

---

src/Spd.Resource.Repository/GDSDApp/GDSDAppRepository.cs

- set innoculations to true for New and Accredited GDSD Team Appl

[SPDBT-4448] default innoculations

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-dog-trainer-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-training-school-ceo.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-training-school-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-accredited-graduation.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-personal-info-anonymous.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-personal-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-personal-info-anonymous.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-personal-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-accredited-school.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/dog-trainer-application.helper.ts

- Dog Trainer allow school edit on renewal
- Put common subheading in a constant
- Fix phone number format on submission

[SPDBT-4423] - GDSD - Dog Trainer allow school edit on renewal

---

src/Spd.Manager.Licence/RetiredDogAppContract.cs

- [SPDBT-4485][GDSD Staging] ConfirmDogLiveWithYouAfterRetire Flag not set in dynamics on Retired Dog renewal

[SPDBT-4485][GDSD Staging] ConfirmDogLiveWithYouAfterRetire Flag not set in dynamics on Retired Dog renewal

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/scss/_material-overrides.scss

[gdsd] focus border color

---

src/Spd.Manager.Licence/DogTrainerAppValidation.cs
src/Spd.Resource.Repository/DogTrainerApp/DogTrainerAppRepository.cs

- [SPDBT-4496] [GDSD Staging] Dog trainer replacement error to accommodate invalid data

[SPDBT-4496] [GDSD Staging] Dog trainer replacement error to accommodate invalid data

---

src/Spd.Utilities.Dynamics/Connected Services/OData Service/ConnectedServiceTemplate.json
src/Spd.Utilities.Dynamics/Connected Services/OData Service/Readme.txt

-[SPDBT-4507]Licensing - Rationale Char Error

[SPDBT-4507]Licensing - Rationale Char Error

---

src/Spd.Manager.Printing/Documents/TransformationStrategies/PersonalLicencePreviewTransformStrategy.cs
src/Spd.Resource.Repository/Document/Contract.cs
src/Spd.Resource.Repository/Document/Mappings.cs

- [SPDBT-4517] Licensing [PROD] - Photo Document URL Skip Face Recognition/Background Removal

[SPDBT-4517] Licensing [PROD] - Photo Document URL Skip Face Recognition/Background Removal

---

src/Spd.Resource.Repository/Licence/Mappings.cs

- [SPDBT-4560] License JSON includes inactive conditions

[SPDBT-4560] License JSON includes inactive conditions
