src/Spd.Resource.Repository/Licence/LicenceRepository.cs
src/Spd.Resource.Repository/LicenceApplication/LicenceApplicationRepository.cs

-all Repo layer GetAsync,  we should not add inactive filter. The inactive in dynamics does not mean it is deleted. There are other meanings like expired, case generated etc. And we needs those inactive record info quite often. So, for GetAsync, no matter it is active or not, we need to return it to Manager layer. Manager can decide we throw exception or return depending on the current business scenario.

fix GetAsync for licence and licenceApp

---

src/Spd.Manager.Licence/LicenceContract.cs
src/Spd.Manager.Licence/LicenceManager.cs
src/Spd.Presentation.Licensing/Controllers/LicenceController.cs
src/Spd.Resource.Repository/Licence/LicenceRepository.cs

- When user do search licence for licence number, we just return the latest licence no matter it is expired or valid. (but not suspended or inactive status)

return latest expired or valid licence

---

src/Spd.Manager.Screening/OrgUserManager.cs

- existing user for screening does not have email, we need to add null check or exception will be thrown

fix empty user email for screening

---

src/Spd.Presentation.Licensing/Controllers/BizLicensingController.cs
src/Spd.Presentation.Licensing/Controllers/SecurityWorkerLicensingController.cs
src/Spd.Presentation.Licensing/Controllers/SessionConstants.cs
src/Spd.Presentation.Licensing/Controllers/SpdApplicantLicenceControllerBase.cs

- This is to support unauth sp app, biz go back to swl flow, we need to save the licenceApp in the cookie to ensure it is one session.

support unauth sp abort biz app

---

src/Spd.Manager.Licence/BizMemberContract.cs
src/Spd.Manager.Licence/BizMemberManager.cs
src/Spd.Manager.Licence/Mappings.cs
src/Spd.Presentation.Licensing/Controllers/BizMembersController.cs
src/Spd.Resource.Repository/BizContact/BizContactRepository.cs
src/Spd.Resource.Repository/BizContact/Contract.cs
src/Spd.Resource.Repository/BizContact/Mappings.cs

- [refactor cm api](spdbt-3011: refactor controlling member api)

refactor biz member management api

---

src/Spd.Manager.Printing/Contract.cs
src/Spd.Manager.Printing/PrintingManager.cs
src/Spd.Presentation.Dynamics/Controllers/PrintingController.cs

-spdbt-2610(Return the JobId in BCMP preview endpoint response header)

return jobId in http response header for licence preview endpoint

---

src/Spd.Resource.Repository/SharedRepositoryFuncs.cs

a solution for SPDBT-3113, we can prevent proceeding app and throw exception, then the app will save with portal status `Draft `and reason `Incomplete`,
currently, however it does not find one category, it proceeds, and app is saved with portal status `Awaiting Payment` and reason `Payment Pending`

[SPDBT-3113] throwing exception when licence category not found

---

src/Spd.Resource.Repository/User/OrgUserRepository.cs

- [SPDBT-3171] When deleting some org user, "value cannot be Null" exception is thrown

[SPDBT-3171] When deleting some org user, "value cannot be Null" exception is thrown

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs

-return response instead of throw bad request.

return response instead of throw bad request for anonymous licence search

---

src/Spd.Manager.Licence/BizProfileManager.cs
src/Spd.Utilities.LogonUser/IPrincipalExtensions.cs

- bceid return all name in name claim, we need to parse it to get the correct fn and ln.

fix bceid user name issue

---

src/Spd.Manager.Licence/BizLicAppValidation.cs

PreviousDocumentIds can be null or empty => BizLicApp

[SPDBT-3234] remove rule for PreviousDocumentIds

---

src/Spd.Manager.Payment/Contract.cs
src/Spd.Presentation.Screening/ClientApp/src/app/api/models/application-payment-response.ts
src/Spd.Presentation.Screening/ClientApp/src/app/api/models/payment-response.ts
src/Spd.Presentation.Screening/ClientApp/src/app/core/code-types/model-desc.models.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/payments.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrp-portal/components/reports.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/crrpa-portal/components/crrpa-payment-fail.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/modules/security-screening-portal/components/security-screening-detail.component.ts
src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/payment-success.component.ts

- Hide 'download receipt' when not applicable
- Add missing FileTypeCode descriptions
- minor UI updates

[SPDBT-3286] download receipt update

---

src/Spd.Presentation.Licensing/ClientApp/src/app/core/code-types/model-desc.models.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/permit-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/core/services/worker-application.service.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-category-private-investigator.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/business-user-applications.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/business-licence-application/components/step-business-licence-checklist-renew.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/step-controlling-member-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/controlling-member-crc/components/step-controlling-member-checklist-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/anonymous/permit-wizard-step-components/step-permit-checklist-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-photograph-of-yourself.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-swl-permit-terms-update-replace.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/common-step-components/common-swl-permit-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-category.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-new.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-renewal.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-checklist-update.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-dogs-authorization.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/modules/personal-licence-application/components/shared/worker-licence-wizard-step-components/step-worker-licence-restraints.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-business-terms.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-fingerprints.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/form-physical-characteristics.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/app/shared/components/payment-success.component.ts
src/Spd.Presentation.Licensing/ClientApp/src/scss/app.scss

- SPDBT-3489 - Terms and Conditions error wording
- SPDBT-3490 - Characteristics defaults
- SPDBT-3491 - Checklists to use bullets
- SPDBT-3492 - Licence categories informational instructions
- SPDBT-3493 - Fingerprint clarification text and button
- SPDBT-3494 - Authorization to use restraints/dogs clarification text
- SPDBT-3495 - Upload photo clarification text
- SPDBT-3496 - Payment received - move Download Receipt button
- SPDBT-3499 - Expired Licence text clarification

[FE] various usability updates

---

src/Spd.Manager.Licence/BizMemberManager.cs
src/Spd.Resource.Repository/BizContact/BizContactRepository.cs
src/Spd.Resource.Repository/BizContact/Contract.cs
src/Spd.Resource.Repository/BizContact/Mappings.cs
src/Spd.Utilities.Dynamics/DynamicsContextLookupHelpers.cs

- [SPDBT-3472] PI showing as employee

[SPDBT-3472] PI showing as employee

---

src/Spd.Manager.Licence/ControllingMemberCrcAppManager.cs
src/Spd.Manager.Licence/Mappings.cs

- [SPDBT-3071] No need to keep history, contact always keeps the latest data of those 3 questions from application.

[SPDBT-3071] No need to keep history, contact always keeps the latest data of those 3 questions from application.

---

src/Spd.Manager.Licence/SecurityWorkerAppManager.cs

- [SPDBT-3543] fix sonar-cube: 'response' is null on at least one execution path.

[SPDBT-3543] fix sonar-cube: 'response' is null on at least one execution path.

---

src/Spd.Resource.Repository/GDSDApp/Mappings.cs

- fix-gdsd get missing mapping usePersonalDogTrainer

fix-gdsd get missing mapping usePersonalDogTrainer

---

src/Spd.Resource.Repository/PersonLicApplication/PersonLicApplicationRepository.cs

- fix 3917(Current/Expired Licence is not showing in SPARC application when applicant is submitting new application)

SPDBT-3917: Current/Expired Licence is not showing in SPARC application when applicant is submitting new application

---

src/Spd.Manager.Licence/LicenceManager.cs

- [SPDBT-3942]licensing: filter out the preview status as valid licence in licence lookup endpoint.

[SPDBT-3942]licensing: filter out the preview status as valid licence in licence lookup endpoint.

---

src/Spd.Presentation.Screening/ClientApp/src/app/shared/components/payment-success.component.ts

- Always show the 'download receipt' button the payment success page.

[SPDBT-3949] Show download receipt

---

src/Spd.Manager.ScheduleJob/ScheduleJobManager.cs

- [SPDBT-4060] Schedule Job Error Handling improvements

[SPDBT-4060] Schedule Job Error Handling improvements

---

src/Spd.Manager.Licence/LicenceManager.cs

- [SPDBT-4074] Return 200 with empty response body for getting licence photo

[SPDBT-4074] Return 200 with empty response body for getting licence photo

---

src/Spd.Manager.Printing/Contract.cs
src/Spd.Manager.Printing/Documents/TransformationStrategies/PersonalLicencePrintingTransformStrategy.cs
src/Spd.Manager.Printing/PrintingManager.cs
src/Spd.Presentation.Dynamics/Controllers/PrintingController.cs
src/Spd.Resource.Repository/Event/Contract.cs
src/Spd.Resource.Repository/Event/EventRepository.cs
src/Spd.Resource.Repository/Event/Mappings.cs
src/Spd.Resource.Repository/Licence/Contract.cs
src/Spd.Resource.Repository/Licence/LicenceRepository.cs
src/Spd.Resource.Repository/Licence/Mappings.cs
src/Spd.Utilities.Printing/BCMailPlus/BcMailPlusApi.cs

-[SPDBT-4113] BMCP-printing cards in batch.

[SPDBT-4113] BMCP-printing cards in batch.

---

src/Spd.Resource.Repository/Document/DocumentRepository.cs

- Release/2.0.0 hotfix2-dog restraints, get documents throws Exception when document url tag is null

Release/2.0.0 hotfix2-dog restraints, get documents throws Exception when document url tag is null

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/authenticated/gdsd-licence-main-licences-list.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/authenticated/gdsd-licence-main.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/dog-trainer-wizard-new-renewal.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/dog-trainer-wizard-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/gdsd-team-wizard-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/retired-dog-wizard-replacement.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/common-application.helper.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/common-application.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/dog-trainer-application.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/gdsd-team-application.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/retired-dog-application.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts

- [SPDBT-4198] add photo to replacement

[SPDBT-4198] add photo to replacement

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/package-lock.json
src/Spd.Presentation.GuideDogServiceDog/ClientApp/package.json
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-application-type.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-licence-access-code.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-landing.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-application-type.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-dog-certification-selection.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-dog-inoculations.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-dog-service-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-dog-tasks.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-licence-access-code.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-mailing-address.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-medical-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-other-trainings.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-school-trainings.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-training-history.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-application-type.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-licence-access-code.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-mailing-address.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-application-type.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/form-photograph-of-yourself-update.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/form-photograph-of-yourself.component.ts

- GDSD language updates
- Remove unneeded entry in packages.json

[SPDBT-3993] GDSD language updates

---

src/Spd.Presentation.GuideDogServiceDog/ClientApp/angular.json
src/Spd.Presentation.GuideDogServiceDog/ClientApp/package-lock.json
src/Spd.Presentation.GuideDogServiceDog/ClientApp/package.json
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/app.module.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-dog-trainer-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/dog-trainer/step-dt-training-school-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/gdsd-team-wizard-new-renewal.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-other-trainings.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-school-trainings.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/gdsd-team/step-team-training-history.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-dog-living-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/retired-dog/step-rd-dog-retired-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-accredited-school.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-dog-info.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-goverment-photo-id.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-personal-info-anonymous.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/components/shared/form-gdsd-terms-of-use.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/constants/constants.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/config.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/gdsd-team-application.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/retired-dog-application.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/core/services/util.service.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/material.module.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/file-upload.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/form-access-code-anonymous.component.ts
src/Spd.Presentation.GuideDogServiceDog/ClientApp/src/app/shared/components/form-address.component.ts

- remove date picker
- change accredited school from dropdown to auto-complete
- add screen reader msg for file upload/removal success

[GDSD] accessibility part-2

---

src/Spd.Presentation.Licensing/Controllers/LicenceController.cs
src/Spd.Resource.Repository/PortalUser/PortalUserRepository.cs
src/Spd.Resource.Repository/User/OrgUserRepository.cs

- [SPDBT-4376] Screening [PROD] - Deactivate the Portal User Invitation when after Identity is created for Portal User
- For Biz Licensing - portal administrator, we did the same, deactivate intivation after user login.

[SPDBT-4376] Screening [PROD] - Deactivate the Portal User Invitation when after Identity is created for Portal User
